const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const defaultState={name:'อาเรีย มูนเฟล',race:'human',className:'เรนเจอร์',face:'soft',mark:'none',eyeStyle:'calm',accessory:'none',hair:'long',body:'average',outfit:'ranger',height:172,hairColor:'#2a1711',skinColor:'#f1c6a8',eyeColor:'#426e58',outfitColor:'#315744',modifier:2,dice:20,round:3,currentTurn:0,journal:'',location:'elderwood',visited:['elderwood'],muted:true,masterVolume:70,ambientVolume:45,effectsVolume:75,soundPreset:'auto',party:[{name:'อาเรีย',role:'เรนเจอร์ · Lv.3',icon:'🧝🏻‍♀️',hp:'24/24',bot:false,location:'elderwood'},{name:'ธีโอ',role:'พ่อมด · Lv.3',icon:'🧙🏽',hp:'17/17',bot:false,location:'moonruins'},{name:'โบริน',role:'นักรบ · Lv.3',icon:'🛡️',hp:'31/31',bot:true,location:'riverrest'}]};
let state={...defaultState,...JSON.parse(localStorage.getItem('mythweave-save')||'{}')};
let socket=null,network={selfId:null,players:[],currentTurnId:null,roomId:null,hostId:null,mode:'new',started:false},selectedSessionMode='new',localReady=false;
function playerIconData(){const skin=state.skinColor||'#f1c6a8',hair=state.hairColor||'#2a1711',eyes=state.eyeColor||'#426e58',cloth=state.outfitColor||'#315744',race=state.race||'human',style=state.hair||'long',outfit=state.outfit||'ranger';const ears=race==='elf'?`<path d="M24 48 3 38l22 27M76 48l21-10-22 27" fill="${skin}" stroke="#b98369"/>`:race==='tiefling'?`<path d="M31 29 19 2l19 23M69 29 81 2 62 25" fill="#493029"/>`:'';const hairPath={short:'M22 45Q22 16 50 14T78 45Q62 31 50 39Q38 29 22 45',long:'M18 70Q12 18 50 13t32 57L70 51Q68 31 50 34T30 51L28 76Z',braid:'M20 47Q21 14 50 13t30 34L69 39Q50 28 30 42M72 42q15 22 1 45q-11-12 0-23q10-10-1-22',mohawk:'M35 31 50 2l15 29Q50 22 35 31'}[style]||'';const outfitMark={ranger:'M37 79 50 92 63 79',knight:'M31 82h38l-6 16H37z',mage:'M35 80q15 18 30 0l8 18H27z'}[outfit];const eyeShape=state.eyeStyle==='fierce'?'M33 46l12 3M55 49l12-3':'M33 48q6-5 12 0M55 48q6-5 12 0';const accessory=state.accessory==='circlet'?'<path d="M28 35q22-12 44 0l-5 7-17-5-17 5z" fill="none" stroke="#ddd4bd" stroke-width="2"/><circle cx="50" cy="36" r="3" fill="#7bc7cb"/>':state.accessory==='earring'?'<circle cx="75" cy="59" r="4" fill="none" stroke="#e8cc82" stroke-width="2"/>':'';const mark=state.mark==='scar'?'<path d="m65 47-8 18" stroke="#a96d68" stroke-width="2"/>':state.mark==='rune'?'<path d="m30 52 6 6-6 6 6 5" fill="none" stroke="#8d63c7" stroke-width="2"/>':'';const glow=state.eyeStyle==='mystic'?`<filter id="g"><feGaussianBlur stdDeviation="2" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>`:'';const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><linearGradient id="b" x2="1" y2="1"><stop stop-color="${cloth}"/><stop offset="1" stop-color="#101c16"/></linearGradient>${glow}</defs><circle cx="50" cy="50" r="49" fill="url(#b)"/><circle cx="50" cy="50" r="45" fill="none" stroke="#d9b86c" stroke-width="2"/>${ears}<path d="M15 100q5-29 35-29t35 29" fill="${cloth}"/><path d="${outfitMark}" fill="#c2a15a" opacity=".85"/><rect x="43" y="62" width="14" height="18" rx="5" fill="${skin}"/><ellipse cx="50" cy="48" rx="27" ry="31" fill="${skin}"/><path d="${hairPath}" fill="${hair}" stroke="${hair}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>${accessory}<path d="${eyeShape}" fill="none" stroke="${eyes}" stroke-width="3.5" stroke-linecap="round" ${state.eyeStyle==='mystic'?'filter="url(#g)"':''}/>${mark}<path d="M43 62q7 5 14 0" fill="none" stroke="#a45f61" stroke-width="2" stroke-linecap="round"/></svg>`;return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function renderPlayerIcon(){const src=playerIconData();$('#worldPlayerIcon').src=src;$('#playerMapIcon').src=src;$('#miniAvatar').innerHTML=`<img src="${src}" alt="ตัวละคร">`;$('#playerTokenName').textContent=state.name.split(' ')[0];if(state.party[0]){state.party[0].name=state.name.split(' ')[0];state.party[0].iconData=src}}
let events=JSON.parse(localStorage.getItem('mythweave-events')||'null')||[
  {text:'<b>ผู้บรรยาย</b> หมอกสีเงินเคลื่อนผ่านซากวิหารอย่างเงียบงัน…',time:'เมื่อครู่'},
  {text:'<b>ธีโอ</b> ตรวจสอบอักขระโบราณบนเสาหิน',time:'2 นาทีที่แล้ว'},
  {text:'<b>โบริน</b> “ข้าได้ยินบางอย่างจากทางเหนือ”',time:'3 นาทีที่แล้ว'}
];
const save=()=>{localStorage.setItem('mythweave-save',JSON.stringify(state));renderParty()};
const toast=t=>{const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(el.t);el.t=setTimeout(()=>el.classList.remove('show'),2200)};
function switchView(name){$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#'+name+'View').classList.add('active');}
$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#openCharacter').onclick=()=>switchView('character');
const locations={
  elderwood:{name:'ป่าเอลเดอร์วูด',icon:'♧',image:'assets/elderwood.png',title:'เสียงกระซิบจากป่าเอลเดอร์วูด',chapter:'บทที่ 1 · คืนเดือนดับ',labels:['⌁ ซากวิหารเอลเดอร์','♧ เส้นทางเก่า'],intro:'หมอกสีเงินหวนกลับมาปกคลุมเส้นทางในป่าต้องมนตร์'},
  riverrest:{name:'หมู่บ้านริเวอร์เรสต์',icon:'⌂',image:'assets/riverrest.png',title:'เงื่อนงำ ณ ริมสายน้ำ',chapter:'บทที่ 2 · แสงสุดท้าย',labels:['⌂ โรงเตี๊ยมปลาคาร์พทอง','≋ สะพานริเวอร์เรสต์'],intro:'เสียงระฆังยามเย็นดังรับคณะเดินทางที่จัตุรัสริมแม่น้ำ'},
  azuredeep:{name:'ถ้ำอาซัวร์ดีพ',icon:'♦',image:'assets/azuredeep.png',title:'ประตูผนึกแห่งอาซัวร์ดีพ',chapter:'บทที่ 3 · แสงใต้พิภพ',labels:['♦ ผลึกสะท้อนจิต','◉ ประตูหินโบราณ'],intro:'แสงคริสตัลสีน้ำเงินเต้นระริกเมื่อเสียงฝีเท้าดังก้องในถ้ำ'},
  nightcrown:{name:'ป้อมไนท์คราวน์',icon:'♜',image:'assets/nightcrown.png',title:'บัลลังก์เหนือพายุ',chapter:'บทที่ 5 · มงกุฎรัตติกาล',labels:['♜ ประตูปราการ','♨ ลานเพลิงนิรันดร์'],intro:'ประตูเหล็กปิดลงเบื้องหลัง ท่ามกลางเสียงฟ้าร้องเหนือปราการ'},
  moonruins:{name:'วิหารจันทรา',icon:'⌁',image:'assets/elderwood.png',title:'บทเพลงแห่งวิหารจันทรา',chapter:'บทที่ 4 · ความทรงจำที่เลือนหาย',labels:['☾ แท่นบูชาจันทรา','⌁ เสาศิลาแตกสลาย'],intro:'รูนโบราณสว่างขึ้นทีละดวงเมื่อคณะเดินทางมาถึงซากวิหาร'}
};
const nodePositions={elderwood:['29%','47%'],nightcrown:['43%','20%'],azuredeep:['75%','29%'],moonruins:['52%','49%'],riverrest:['51%','75%']};
function renderWorldParty(){const layer=$('#partyPositionLayer');layer.innerHTML='';const members=network.players.length?network.players.filter(m=>m.id!==network.selfId):state.party.slice(1);members.forEach((m,i)=>{const location=m.location||state.location,[x,y]=nodePositions[location]||nodePositions.elderwood,pin=document.createElement('button');pin.className='member-world-pin';pin.style.left=x;pin.style.top=y;pin.style.setProperty('--offset',(i%3-1)*34+'px');pin.innerHTML=`<span>${m.iconData?`<img src="${m.iconData}" alt="">`:m.icon||'◆'}</span><b>${m.name}</b><small>${locations[location]?.name||''}</small>`;pin.title=`${m.name} อยู่ที่ ${locations[location]?.name||''}`;layer.append(pin)})}
function renderLocation(){const l=locations[state.location]||locations.elderwood;renderPlayerIcon();$('#sceneImage').src=l.image;$('#sceneImage').alt='ฉาก'+l.name;$('#sceneTitle').textContent=l.title;$('#sceneChapter').textContent=l.chapter;$('#locationLabel1').innerHTML=`<span>${l.labels[0].split(' ')[0]}</span> ${l.labels[0].split(' ').slice(1).join(' ')}`;$('#locationLabel2').innerHTML=`<span>${l.labels[1].split(' ')[0]}</span> ${l.labels[1].split(' ').slice(1).join(' ')}`;$('#currentLocationName').textContent=l.name;$('#currentLocationIcon').textContent=l.icon;const [x,y]=nodePositions[state.location];$('#travelerMarker').style.left=x;$('#travelerMarker').style.top=y;$$('.world-node').forEach(n=>{n.classList.toggle('current',n.dataset.location===state.location);n.classList.toggle('visited',(state.visited||[]).includes(n.dataset.location))});const explored=Math.round(((state.visited||[]).length/Object.keys(locations).length)*100);$('#explorePercent').textContent=explored+'%';$('#exploreBar').style.width=explored+'%';renderWorldParty();updateSoundUI()}
function travelTo(id){if(id===state.location){toast('คุณอยู่ที่นี่แล้ว');return}const l=locations[id],overlay=$('#travelOverlay');$('#travelDestination').textContent=l.name;overlay.classList.add('active');playFx('travel');setTimeout(()=>{state.location=id;if(state.party[0])state.party[0].location=id;state.visited=[...new Set([...(state.visited||[]),id])];save();socket?.emit('player-update',{location:id});renderLocation();if(!state.muted)startAmbience();overlay.classList.remove('active');switchView('table');addEvent(`<b>${state.name.split(' ')[0]}</b> เดินทางถึง ${l.name} — ${l.intro}`);toast('เดินทางถึง '+l.name+' แล้ว ✦')},1450)}
$$('.world-node').forEach(n=>n.onclick=()=>travelTo(n.dataset.location));$('#openWorldMap').onclick=()=>switchView('world');$('#returnToScene').onclick=()=>switchView('table');
function renderParty(){const p=$('#partyList');p.innerHTML='';const online=network.players.length?network.players.map(m=>({...m,role:'ผู้เล่นออนไลน์',hp:'ONLINE'})):state.party;online.forEach((m,i)=>{const el=document.createElement('div'),active=network.players.length?m.id===network.currentTurnId:i===(state.currentTurn||0);el.className='party-member'+(m.bot?' bot':'')+(active?' active-turn':'');const portrait=m.iconData?`<img src="${m.iconData}" alt="${m.name}">`:m.icon;const place=locations[m.location||state.location]?.name||'ไม่ทราบตำแหน่ง';el.innerHTML=`<span class="portrait">${portrait||'◆'}</span><span><b>${m.name}${m.bot?' · AI':''}</b><small>${m.role}</small><small class="member-place">⌖ ${place}</small></span><span class="hp">${m.hp==='ONLINE'?'● ออนไลน์':'♥ '+m.hp}</span>`;el.style.animationDelay=i*50+'ms';p.append(el)});$('#onlineCount').textContent=network.players.length||state.party.length}
function renderEvents(){const log=$('#eventLog');log.innerHTML=events.map(e=>`<div class="event ${e.roll?'roll':''}">${e.text}${e.result?`<strong>${e.result}</strong>`:''}<small>${e.time}</small></div>`).join('');log.scrollTop=log.scrollHeight;localStorage.setItem('mythweave-events',JSON.stringify(events))}
function addEvent(text,extra={}){events.push({text,time:'ตอนนี้',...extra});if(events.length>30)events.shift();renderEvents()}
renderParty();renderEvents();
$('#copyInvite').onclick=async()=>{const link=location.href.split('#')[0]+'#room='+$('#roomCode').textContent;try{await navigator.clipboard.writeText(link);toast('คัดลอกลิงก์เชิญแล้ว ✦')}catch{toast('รหัสห้อง: '+$('#roomCode').textContent)}};
$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput'),v=input.value.trim();if(!v)return;if(socket?.connected)socket.emit('chat-send',v);else addEvent(`<b>${state.name.split(' ')[0]}</b> “${v.replace(/[<>]/g,'')}”`);input.value=''};
$('#clearLog').onclick=()=>{events=[];renderEvents();toast('ล้างบันทึกเหตุการณ์แล้ว')};
let selectedBot={name:'Lyra',role:'Cleric',icon:'🧝🏼‍♀️'};$('#addBotBtn').onclick=()=>$('#botModal').classList.add('open');$$('[data-close]').forEach(b=>b.onclick=()=>$('#botModal').classList.remove('open'));$('#botModal').onclick=e=>{if(e.target.id==='botModal')e.currentTarget.classList.remove('open')};
$$('.bot-choices button').forEach(b=>b.onclick=()=>{$$('.bot-choices button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedBot={name:b.dataset.bot,role:b.dataset.role,icon:b.querySelector('span').textContent}});
$('#confirmBot').onclick=()=>{const names={Lyra:'ไลรา',Grimm:'กริมม์',Ember:'เอ็มเบอร์'},roles={Cleric:'คลีริก · Lv.3',Rogue:'โร้ก · Lv.3',Sorcerer:'ซอร์เซอเรอร์ · Lv.3'};if(state.party.some(p=>p.name===names[selectedBot.name]))return toast('บอทคนนี้อยู่ในปาร์ตี้แล้ว');state.party.push({name:names[selectedBot.name],role:roles[selectedBot.role],icon:selectedBot.icon,hp:'22/22',bot:true,location:state.location});save();renderWorldParty();$('#botModal').classList.remove('open');addEvent(`<b>${names[selectedBot.name]} · AI</b> เข้าร่วมคณะเดินทางที่ ${locations[state.location].name}`);playFx('chime');toast('เพิ่มบอทเข้าปาร์ตี้แล้ว')};
let zoom=100;function setZoom(){zoom=Math.max(80,Math.min(140,zoom));$('#zoomLevel').textContent=zoom+'%';$('#mapFrame>img').style.transform=`scale(${zoom/100})`}$('#zoomIn').onclick=()=>{zoom+=10;setZoom()};$('#zoomOut').onclick=()=>{zoom-=10;setZoom()};$('#gridToggle').onclick=e=>{e.currentTarget.classList.toggle('active');$('.grid-overlay').classList.toggle('off')};
$$('.token').forEach(t=>{t.onclick=()=>{$$('.token').forEach(x=>x.classList.remove('selected'));t.classList.add('selected')};let drag=false;t.onpointerdown=e=>{drag=true;t.setPointerCapture(e.pointerId)};t.onpointermove=e=>{if(!drag)return;const r=$('#mapFrame').getBoundingClientRect();t.style.left=((e.clientX-r.left)/r.width*100)+'%';t.style.top=((e.clientY-r.top)/r.height*100)+'%'};t.onpointerup=()=>drag=false});
function currentTurnPlayer(){return network.players.length?network.players.find(p=>p.id===network.currentTurnId):state.party[state.currentTurn||0]}
function updateTurnUI(){const player=currentTurnPlayer()||state.party[0],online=network.players.length>0,mine=online?network.started&&player?.id===network.selfId:(state.currentTurn||0)===0;let icon=player?.iconData;if(!icon){const emoji=player?.icon||'◆',svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><circle cx="32" cy="32" r="31" fill="#183025"/><text x="32" y="43" font-size="34" text-anchor="middle">${emoji}</text></svg>`;icon='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}$('#turnAvatar').src=icon;$('#turnPlayerName').textContent=player?.name||'กำลังรอผู้เล่น';$('#turnStatus').textContent=online&&!network.started?'รอเริ่มเกม':mine?'ถึงตาของคุณ':'กำลังรอเทิร์น';$('#endTurn').disabled=!mine;$('#endTurn').textContent=online&&!network.started?'อยู่ในล็อบบี้':mine?'จบเทิร์น →':`รอ ${player?.name||'ผู้เล่น'}…`;$('#rollDice').disabled=!mine;$('#rollDice').classList.toggle('waiting',!mine);renderParty()}
function showBoardRoll(result){const die=$('#boardDice');$('#boardDiceResult').textContent=result.raw;$('#boardDiceFormula').textContent=`D${result.sides} ${result.modifier>=0?'+':''}${result.modifier} = ${result.total}`;$('#boardDiceOwner').textContent=`${result.rollerName} ทอยได้ ${result.total}`;die.classList.remove('rolling','show');void die.offsetWidth;die.classList.add('rolling');playFx('dice');setTimeout(()=>die.classList.add('show'),900);setTimeout(()=>die.classList.remove('rolling','show'),4200);addEvent(`<b>${result.rollerName}</b> ทอย D${result.sides} (${result.raw} ${result.modifier>=0?'+':''}${result.modifier})`,{roll:true,result:result.total});if(result.raw===result.sides){setTimeout(()=>playFx('chime'),450);toast(`${result.rollerName} คริติคอล! ✦`)}}
function offlineCompanionTurn(){const player=currentTurnPlayer();if((state.currentTurn||0)===0||!player)return;setTimeout(()=>{const sides=20,raw=Math.floor(Math.random()*sides)+1,modifier=player.bot?1:3;showBoardRoll({rollerName:player.name,sides,raw,modifier,total:raw+modifier});setTimeout(()=>{state.currentTurn=(state.currentTurn+1)%state.party.length;if(state.currentTurn===0)state.round++;save();seconds=90;updateTurnUI();offlineCompanionTurn()},1800)},900)}
$('#endTurn').onclick=()=>{if(socket?.connected)socket.emit('end-turn');else{state.currentTurn=((state.currentTurn||0)+1)%state.party.length;if(state.currentTurn===0)state.round++;$('#roundNumber').textContent=String(state.round).padStart(2,'0');save();seconds=90;updateTurnUI();addEvent(`<b>จบเทิร์น</b> ถึงตาของ ${currentTurnPlayer().name}`);offlineCompanionTurn()}};
let seconds=88;setInterval(()=>{seconds=seconds<=0?90:seconds-1;$('#turnTimer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')},1000);
$$('#diceList button').forEach(b=>b.onclick=()=>{$$('#diceList button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.dice=+b.dataset.sides;$('.roll-btn small').nextSibling.textContent='ทอย D'+state.dice;$('.d20').textContent=state.dice;save()});
function updateMod(n){state.modifier=Math.max(-5,Math.min(10,state.modifier+n));$('#modifierValue').textContent=(state.modifier>=0?'+':'')+state.modifier;save()}$('#minusMod').onclick=()=>updateMod(-1);$('#plusMod').onclick=()=>updateMod(1);
$('#rollDice').onclick=()=>{if(socket?.connected){socket.emit('roll-request',{sides:state.dice,modifier:state.modifier});return}if((state.currentTurn||0)!==0)return toast('ยังไม่ถึงเทิร์นของคุณ');const raw=Math.floor(Math.random()*state.dice)+1;showBoardRoll({rollerName:state.name.split(' ')[0],sides:state.dice,raw,modifier:state.modifier,total:raw+state.modifier})};
function selectGroup(id,key,cb){$$(`#${id} button`).forEach(b=>b.onclick=()=>{$$(`#${id} button`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state[key]=b.dataset.value;cb?.(state[key])})}
$$('#customTabs button').forEach(b=>b.onclick=()=>{$$('#customTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane===b.dataset.tab))});
const avatar=$('#characterAvatar');
selectGroup('raceOptions','race',v=>{avatar.className=avatar.className.replace(/race-\w+/,'race-'+v)});selectGroup('faceOptions','face',v=>{avatar.className=avatar.className.replace(/face-\w+/g,'').trim()+(v==='soft'?'':' face-'+v)});selectGroup('eyeOptions','eyeStyle',v=>{avatar.className=avatar.className.replace(/eyes-\w+/g,'').trim()+' eyes-'+v});selectGroup('markOptions','mark',v=>{avatar.className=avatar.className.replace(/mark-\w+/g,'').trim()+(v==='none'?'':' mark-'+v)});selectGroup('accessoryOptions','accessory',v=>{$('.accessory',avatar).className='accessory accessory-'+v});selectGroup('hairOptions','hair',v=>{$('.hair',avatar).className='hair hair-'+v});selectGroup('bodyOptions','body',v=>{avatar.className=avatar.className.replace(/body-\w+/,'body-'+v)});selectGroup('outfitOptions','outfit',v=>{$('.armor',avatar).className='armor armor-'+v});selectGroup('hairColors','hairColor',v=>document.documentElement.style.setProperty('--hair',v));selectGroup('skinColors','skinColor',v=>document.documentElement.style.setProperty('--skin',v));selectGroup('eyeColors','eyeColor',v=>document.documentElement.style.setProperty('--eyes',v));selectGroup('outfitColors','outfitColor',v=>document.documentElement.style.setProperty('--outfit',v));
$('#heightRange').oninput=e=>{$('#heightOutput').value=e.target.value+' ซม.';state.height=+e.target.value;avatar.style.scale=.88+(state.height-145)/200};
$('#characterName').oninput=e=>{$('#avatarNameDisplay').textContent=e.target.value||'ไร้นาม'};$('#classSelect').onchange=e=>{$('#avatarSubtitle').textContent=$('#raceOptions .selected b').textContent+' · '+e.target.value};
$('#saveCharacter').onclick=()=>{state.name=$('#characterName').value.trim()||'นักผจญภัยไร้นาม';state.className=$('#classSelect').value;renderPlayerIcon();save();socket?.emit('player-update',{name:state.name.split(' ')[0],iconData:playerIconData()});renderLocation();$('#avatarNameDisplay').textContent=state.name;$('#miniName').textContent=state.name.split(' ')[0];$('#avatarSubtitle').textContent=$('#raceOptions .selected b').textContent+' · '+state.className;playFx('chime');toast('บันทึกตัวละครและอัปเดตไอคอนแล้ว ✦')};
$('#journalText').value=state.journal;let journalTimer;$('#journalText').oninput=e=>{state.journal=e.target.value;$('#saveStatus').textContent='กำลังเขียน…';clearTimeout(journalTimer);journalTimer=setTimeout(()=>{save();$('#saveStatus').textContent='บันทึกอัตโนมัติแล้ว'},700)};$('#saveJournal').onclick=()=>{state.journal=$('#journalText').value;save();$('#saveStatus').textContent='บันทึกแล้วเมื่อสักครู่';toast('บันทึกแคมเปญแล้ว')};

// Procedural audio: no external audio files and every channel is user controlled.
let audioCtx,masterGain,ambientGain,effectsGain,ambientNodes=[];
const locationSounds={elderwood:'forest',moonruins:'forest',riverrest:'tavern',azuredeep:'cave',nightcrown:'rain'};
function initAudio(){if(audioCtx)return;audioCtx=new (window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();ambientGain=audioCtx.createGain();effectsGain=audioCtx.createGain();ambientGain.connect(masterGain);effectsGain.connect(masterGain);masterGain.connect(audioCtx.destination);applyVolumes()}
function applyVolumes(){if(!audioCtx)return;const t=audioCtx.currentTime;masterGain.gain.setTargetAtTime(state.muted?0:(state.masterVolume??70)/100,t,.03);ambientGain.gain.setTargetAtTime((state.ambientVolume??45)/100,t,.03);effectsGain.gain.setTargetAtTime((state.effectsVolume??75)/100,t,.03)}
function stopAmbience(){ambientNodes.forEach(n=>{try{n.stop()}catch{}});ambientNodes=[]}
function startAmbience(){if(state.muted)return;initAudio();audioCtx.resume();stopAmbience();const mode=state.soundPreset==='auto'?(locationSounds[state.location]||'forest'):state.soundPreset,seconds=3,buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*seconds,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.16;const noise=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),bed=audioCtx.createGain();noise.buffer=buffer;noise.loop=true;filter.type=mode==='rain'?'highpass':'lowpass';filter.frequency.value={forest:900,rain:1800,tavern:520,cave:280}[mode]||700;bed.gain.value={forest:.22,rain:.3,tavern:.12,cave:.15}[mode]||.2;noise.connect(filter).connect(bed).connect(ambientGain);noise.start();ambientNodes.push(noise);const osc=audioCtx.createOscillator(),tone=audioCtx.createGain();osc.type=mode==='cave'?'sine':'triangle';osc.frequency.value={forest:174,rain:82,tavern:220,cave:110}[mode]||150;tone.gain.value=mode==='rain'?.012:.018;osc.connect(tone).connect(ambientGain);osc.start();ambientNodes.push(osc)}
function playFx(kind='chime'){if(state.muted)return;initAudio();audioCtx.resume();const now=audioCtx.currentTime,notes=kind==='dice'?[155,118,90]:kind==='travel'?[196,247,330]:[440,554,659];notes.forEach((freq,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=kind==='dice'?'square':'sine';o.frequency.setValueAtTime(freq,now+i*.07);if(kind==='dice')o.frequency.exponentialRampToValueAtTime(Math.max(55,freq*.55),now+.12+i*.07);g.gain.setValueAtTime(kind==='dice'?.075:.055,now+i*.07);g.gain.exponentialRampToValueAtTime(.001,now+.22+i*.1);o.connect(g).connect(effectsGain);o.start(now+i*.07);o.stop(now+.28+i*.1)})}
function updateSoundUI(){const enabled=!state.muted,place=locations[state.location]?.name||'';$('#soundToggleIcon').textContent=enabled?'♫':'♪';$('#soundToggleLabel').textContent=enabled?'กำลังเล่นเสียง':'เปิดเสียง';$('#soundSceneLabel').textContent='บรรยากาศ'+place;$('#masterToggle').classList.toggle('playing',enabled);$('#soundBtn').classList.toggle('active',enabled);$('#soundBtn').textContent=enabled?'♫':'♪';[['masterVolume','masterOutput','masterVolume'],['ambientVolume','ambientOutput','ambientVolume'],['effectsVolume','effectsOutput','effectsVolume']].forEach(([id,out,key])=>{$('#'+id).value=state[key]??defaultState[key];$('#'+out).value=(state[key]??defaultState[key])+'%'});$$('#soundPresets button').forEach(b=>b.classList.toggle('selected',b.dataset.sound===(state.soundPreset||'auto')))}
$('#soundBtn').onclick=()=>{$('#soundModal').classList.add('open');updateSoundUI()};$('#closeSound').onclick=()=>$('#soundModal').classList.remove('open');$('#soundModal').onclick=e=>{if(e.target.id==='soundModal')e.currentTarget.classList.remove('open')};
$('#masterToggle').onclick=()=>{state.muted=!state.muted;if(!state.muted){initAudio();audioCtx.resume();startAmbience();playFx('chime')}else{applyVolumes();stopAmbience()}save();updateSoundUI()};
[['masterVolume','masterVolume'],['ambientVolume','ambientVolume'],['effectsVolume','effectsVolume']].forEach(([id,key])=>{$('#'+id).oninput=e=>{state[key]=+e.target.value;$('#'+id.replace('Volume','Output')).value=e.target.value+'%';applyVolumes();save()}});
$$('#soundPresets button').forEach(b=>b.onclick=()=>{state.soundPreset=b.dataset.sound;$$('#soundPresets button').forEach(x=>x.classList.toggle('selected',x===b));save();if(!state.muted){startAmbience();playFx('chime')}});$('#testSound').onclick=()=>{if(state.muted){state.muted=false;initAudio();startAmbience();updateSoundUI()}playFx('chime');save()};
function hydrate(){state.location=state.location||'elderwood';state.visited=state.visited||['elderwood'];state.currentTurn=Number.isInteger(state.currentTurn)?state.currentTurn:0;['eyeStyle','accessory','outfit','eyeColor','outfitColor'].forEach(key=>state[key]=state[key]||defaultState[key]);const starterPlaces=['elderwood','moonruins','riverrest'];state.party.forEach((m,i)=>m.location=m.location||(i===0?state.location:starterPlaces[i%starterPlaces.length]));state.party[0].location=state.location;avatar.className=`character-avatar body-${state.body} race-${state.race} eyes-${state.eyeStyle}${state.face!=='soft'?' face-'+state.face:''}${state.mark!=='none'?' mark-'+state.mark:''}`;$('.hair',avatar).className='hair hair-'+state.hair;$('.armor',avatar).className='armor armor-'+state.outfit;$('.accessory',avatar).className='accessory accessory-'+state.accessory;document.documentElement.style.setProperty('--hair',state.hairColor);document.documentElement.style.setProperty('--skin',state.skinColor);document.documentElement.style.setProperty('--eyes',state.eyeColor);document.documentElement.style.setProperty('--outfit',state.outfitColor);$('#characterName').value=state.name;$('#avatarNameDisplay').textContent=state.name;$('#miniName').textContent=state.name.split(' ')[0];$('#classSelect').value=state.className;$('#heightRange').value=state.height;$('#heightOutput').value=state.height+' ซม.';$('#modifierValue').textContent=(state.modifier>=0?'+':'')+state.modifier;$('#roundNumber').textContent=String(state.round).padStart(2,'0');[['raceOptions',state.race],['faceOptions',state.face],['eyeOptions',state.eyeStyle],['markOptions',state.mark],['accessoryOptions',state.accessory],['hairOptions',state.hair],['bodyOptions',state.body],['outfitOptions',state.outfit],['hairColors',state.hairColor],['skinColors',state.skinColor],['eyeColors',state.eyeColor],['outfitColors',state.outfitColor]].forEach(([id,v])=>{$$(`#${id} button`).forEach(b=>b.classList.toggle('selected',b.dataset.value===v))});renderPlayerIcon();renderLocation();renderParty();updateSoundUI();updateTurnUI()}hydrate();
const channel='BroadcastChannel'in window?new BroadcastChannel('mythweave-room'):null;if(channel){channel.onmessage=e=>{if(!socket?.connected&&e.data?.type==='chat'){events=e.data.events;renderEvents()}};const original=addEvent;addEvent=(text,extra={})=>{original(text,extra);if(!socket?.connected)channel.postMessage({type:'chat',events})}}
function renderLobby(){if(!network.players.length)return;$('#lobbyRoomCode').textContent=network.roomId||'MOON-742';$('#lobbyModeIcon').textContent=network.mode==='resume'?'↻':'✦';$('#lobbyModeText').textContent=network.mode==='resume'?'เล่นต่อจากเซฟล่าสุด':'เริ่มการผจญภัยใหม่';const list=$('#lobbyPlayers');list.innerHTML=network.players.map(player=>`<div class="lobby-player ${player.ready?'ready':''} ${player.id===network.selfId?'self':''}"><img src="${player.iconData||playerIconData()}" alt="${player.name}"><div><b>${player.name}${player.id===network.hostId?' · โฮสต์':''}</b><small>${locations[player.location]?.name||'กำลังเตรียมตัวละคร'}</small></div><span>${player.ready?'● พร้อม':'○ ยังไม่พร้อม'}</span></div>`).join('');const me=network.players.find(p=>p.id===network.selfId);localReady=Boolean(me?.ready);$('#readyBtn').classList.toggle('ready',localReady);$('#readyBtn').textContent=localReady?'✓ พร้อมแล้ว — กดเพื่อยกเลิก':'✓ ฉันพร้อมแล้ว';const isHost=network.selfId===network.hostId,allReady=network.players.length>0&&network.players.every(p=>p.ready);$('#startGameBtn').style.display=isHost?'block':'none';$('#startGameBtn').disabled=!allReady;$('#startGameBtn').textContent=allReady?'เริ่มการผจญภัย ✦':'รอผู้เล่นทุกคนพร้อม…';$('#readyHint').textContent=isHost?'คุณเป็นโฮสต์ — เริ่มเกมได้เมื่อทุกคนพร้อม':'รอให้โฮสต์เริ่มเกม';if(network.started)$('#joinModal').classList.remove('open')}
function applyCampaignStart(data){if(data.mode==='new'){state.location='elderwood';state.visited=['elderwood'];state.round=1;state.currentTurn=0;events=[{text:'<b>ผู้บรรยาย</b> การผจญภัยบทใหม่ได้เริ่มขึ้นแล้ว…',time:'ตอนนี้'}]}else if(data.campaign){const c=data.campaign;state.location=c.location||state.location;state.visited=Array.isArray(c.visited)?c.visited:state.visited;state.round=Number(c.round)||state.round;state.journal=typeof c.journal==='string'?c.journal:state.journal;$('#journalText').value=state.journal}save();renderLocation();renderEvents();$('#roundNumber').textContent=String(state.round).padStart(2,'0');$('#joinModal').classList.remove('open');switchView('table');playFx('chime');toast(data.mode==='resume'?'โหลดการผจญภัยล่าสุดแล้ว':'การผจญภัยเริ่มขึ้นแล้ว ✦')}
function connectOnline(){if(typeof io!=='function')return;const hashParams=new URLSearchParams(location.hash.slice(1)),roomId=(hashParams.get('room')||$('#roomCode').textContent||'MOON-742').toUpperCase();$('#joinRoomCode').textContent=roomId;$('#joinName').value=state.name.split(' ')[0];$('#joinModal').classList.add('open');$$('#sessionChoices button').forEach(button=>button.onclick=()=>{$$('#sessionChoices button').forEach(x=>x.classList.toggle('selected',x===button));selectedSessionMode=button.dataset.mode});socket=io({autoConnect:false});socket.on('connect',()=>{const clientId=sessionStorage.getItem('mythweave-client')||crypto.randomUUID();sessionStorage.setItem('mythweave-client',clientId);socket.emit('join-room',{roomId,mode:selectedSessionMode,campaign:{location:state.location,visited:state.visited,round:state.round,journal:state.journal},player:{clientId,name:state.name.split(' ')[0],iconData:playerIconData(),location:state.location}})});socket.on('joined-room',data=>{network.selfId=data.selfId;network.roomId=data.roomId;$('#roomCode').textContent=data.roomId;$('#joinStage').style.display='none';$('#lobbyStage').classList.add('active');$('.connection-note').innerHTML='<i></i> อยู่ในล็อบบี้ออนไลน์';toast('เข้าสู่ล็อบบี้ '+data.roomId+' แล้ว')});socket.on('room-state',data=>{network.players=data.players||[];network.currentTurnId=data.currentTurnId;network.hostId=data.hostId;network.mode=data.mode||'new';network.started=Boolean(data.started);seconds=90;renderLobby();renderParty();renderWorldParty();updateTurnUI()});socket.on('game-started',applyCampaignStart);socket.on('dice-rolled',showBoardRoll);socket.on('chat-event',data=>addEvent(`<b>${data.name}</b> “${data.text}”`));socket.on('system-event',data=>addEvent(`<b>ห้องเกม</b> ${data.text}`));socket.on('action-error',toast);socket.on('connect_error',()=>{$('#joinConfirm').disabled=false;$('#joinConfirm').textContent='ลองเชื่อมต่ออีกครั้ง';toast('ยังเชื่อมต่อไม่ได้ กรุณารอสักครู่แล้วลองใหม่')});socket.on('disconnect',()=>{$('.connection-note').textContent='กำลังเชื่อมต่อใหม่…';network.players=[];network.currentTurnId=null;renderParty();updateTurnUI()});$('#joinConfirm').onclick=()=>{const name=$('#joinName').value.trim();if(!name){toast('กรุณาใส่ชื่อผู้เล่น');$('#joinName').focus();return}state.name=name;renderPlayerIcon();save();$('#miniName').textContent=name.split(' ')[0];$('#joinConfirm').disabled=true;$('#joinConfirm').textContent='กำลังเข้าห้อง…';socket.connect()};$('#joinName').onkeydown=e=>{if(e.key==='Enter')$('#joinConfirm').click()};$('#joinOffline').onclick=()=>{$('#joinModal').classList.remove('open');socket.close();socket=null;toast('เข้าสู่โหมดทดลองออฟไลน์')};$('#readyBtn').onclick=()=>socket?.emit('player-ready',!localReady);$('#startGameBtn').onclick=()=>socket?.emit('start-game')}
connectOnline();
const previewParams=new URLSearchParams(location.search),initialView=previewParams.get('view');if(['world','character','journal','table'].includes(initialView))switchView(initialView);if(previewParams.get('offline')==='1'){$('#joinModal').classList.remove('open');if(socket){socket.close();socket=null}}
