"use client";
import Link from "next/link";
import {useMemo,useState} from "react";

type Character={id:string;name:string;level:number;race:string};
type Entry={id:string;monster_name:string;biome:string;signature_trait:string;encounter_count:number;notes:string;discovered_weakness:string|null;updated_at?:string;share_mode?:string;created_at?:string};
type Item={id:number;name_th:string;name_en:string;rarity:string;category:string;base_value:number;weight:number;tags:string[];properties:Record<string,unknown>};
type Relic={id:string;name_th:string;rarity:string;category:string;power_rating:number;properties:Record<string,unknown>;created_at:string};
type Lore={race_id:string;name_th:string;title_th:string;summary_th:string;motto_th:string;sigil:string;accent_color:string};
type Tab="bestiary"|"items"|"lore"|"rates";
const tabs:Array<[Tab,string,string]>=[["bestiary","อสูร","BESTIARY"],["items","ไอเทม","ITEM ARCHIVE"],["lore","ตำนาน","RACE LORE"],["rates","อัตราดรอป","DROP RATES"]];
const rarityThai:Record<string,string>={common:"ธรรมดา",uncommon:"ไม่ธรรมดา",rare:"หายาก",epic:"มหากาพย์",legendary:"ตำนาน",soulbound:"ผูกวิญญาณ"};

export function CodexClient({characters,character,entries,shares,items,relics,lore,initialTab}:{characters:Character[];character:Character;entries:Entry[];shares:Entry[];items:Item[];relics:Relic[];lore:Lore[];initialTab:Tab}){
  const[tab,setTab]=useState<Tab>(initialTab);const[query,setQuery]=useState("");const needle=query.trim().toLocaleLowerCase("th");
  const bestiary=useMemo(()=>[...entries,...shares].filter(item=>`${item.monster_name} ${item.biome} ${item.notes}`.toLocaleLowerCase("th").includes(needle)),[entries,shares,needle]);
  const visibleItems=useMemo(()=>items.filter(item=>`${item.name_th} ${item.name_en} ${item.category} ${item.rarity}`.toLocaleLowerCase("th").includes(needle)),[items,needle]);
  const poolTotals=useMemo(()=>items.reduce<Record<string,number>>((total,item)=>({...total,[item.category]:(total[item.category]??0)+item.weight}),{}),[items]);
  const forgeRates=useMemo(()=>{const boost=Math.min(character.level,10);const count=(min:number,max:number)=>Array.from({length:100},(_,index)=>index+1+boost).filter(value=>value>=min&&value<=max).length;return[{rarity:"legendary",value:count(108,999)},{rarity:"epic",value:count(98,107)},{rarity:"rare",value:count(85,97)},{rarity:"uncommon",value:count(60,84)},{rarity:"common",value:count(-999,59)}]},[character.level]);
  return <main className="codex-shell"><header><Link href={`/characters/${character.id}`}>← Character Sheet</Link><span>MYTHWEAVE · GRAND CODEX</span><select aria-label="เลือกตัวละคร" value={character.id} onChange={event=>location.href=`/codex?character=${event.target.value}`}>{characters.map(hero=><option value={hero.id} key={hero.id}>{hero.name}</option>)}</select></header><section className="codex-hero"><div><small>THE KNOWLEDGE YOU HAVE EARNED</small><h1>มหาคัมภีร์<br/><em>Mythweave</em></h1><p>รวมเฉพาะความรู้ที่ {character.name} ค้นพบ ได้รับแบ่งปัน หรือเข้าถึงได้ในโลกนี้</p></div><div className="codex-seal"><b>MW</b><span>LV {character.level}</span></div></section><nav className="codex-tabs">{tabs.map(([id,label,kicker])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><small>{kicker}</small><b>{label}</b></button>)}</nav><div className="codex-search"><span>⌕</span><input aria-label="ค้นหา Codex" value={query} onChange={event=>setQuery(event.target.value)} placeholder="ค้นหาชื่อ หมวดหมู่ พื้นที่ หรือบันทึก…"/><i>{tab==="bestiary"?bestiary.length:tab==="items"?visibleItems.length:tab==="lore"?lore.length:items.length} RECORDS</i></div>
  {tab==="bestiary"&&<section className="codex-grid bestiary-index">{bestiary.length?bestiary.map(item=><article key={`${item.share_mode??"own"}-${item.id}`}><small>{item.share_mode?`${item.share_mode.toUpperCase()} SHARE`:"FIELD RECORD"} · {item.biome}</small><h2>{item.monster_name}</h2><strong>{item.discovered_weakness?`จุดอ่อน · ${item.discovered_weakness}`:"จุดอ่อนยังไม่ยืนยัน"}</strong><p>{item.notes||item.signature_trait}</p><footer><span>พบ {item.encounter_count} ครั้ง</span><i>{item.signature_trait}</i></footer></article>):<Empty text="ยังไม่มีบันทึกอสูรที่ตรงกับการค้นหา"/>}</section>}
  {tab==="items"&&<section className="codex-grid item-index">{relics.map(item=><article className={item.rarity} key={item.id}><small>OWNED RELIC · {item.category}</small><h2>{item.name_th}</h2><strong>POWER {item.power_rating}</strong><p>{rarityThai[item.rarity]??item.rarity}</p></article>)}{visibleItems.map(item=><article className={item.rarity} key={item.id}><small>{item.category} · {rarityThai[item.rarity]??item.rarity}</small><h2>{item.name_th}</h2><span>{item.name_en}</span><p>มูลค่าพื้นฐาน {item.base_value} CP</p><footer>{item.tags.map(tag=><i key={tag}>{tag}</i>)}</footer></article>)}</section>}
  {tab==="lore"&&<section className="codex-grid lore-index">{lore.filter(item=>`${item.name_th} ${item.title_th} ${item.summary_th}`.toLocaleLowerCase("th").includes(needle)).map(item=><Link href={`/lore/races/${item.race_id}?character=${character.id}`} style={{"--race":item.accent_color} as React.CSSProperties} key={item.race_id}><b>{item.sigil}</b><small>{item.title_th}</small><h2>{item.name_th}</h2><p>{item.summary_th}</p><blockquote>“{item.motto_th}”</blockquote></Link>)}</section>}
  {tab==="rates"&&<section className="rate-layout"><article className="forge-rates"><header><small>EXACT · LEVEL {character.level}</small><h2>Relic Forge rarity</h2><p>คำนวณจากผลสุ่ม 100 ค่าและโบนัสเลเวลของตัวละคร</p></header>{forgeRates.map(rate=><div key={rate.rarity}><span>{rarityThai[rate.rarity]}</span><i><b style={{width:`${rate.value}%`}}/></i><strong>{rate.value}%</strong></div>)}</article><article className="pool-rates"><header><small>WEIGHTED CONTENT POOL</small><h2>อัตราปรากฏของไอเทม</h2><p>เปอร์เซ็นต์สัมพัทธ์ภายในหมวดเดียวกัน ไม่ใช่อัตราดรอปจากมอนสเตอร์</p></header>{visibleItems.map(item=><div key={item.id}><span><b>{item.name_th}</b><small>{item.category} · W{item.weight}</small></span><strong>{((item.weight/(poolTotals[item.category]||1))*100).toFixed(1)}%</strong></div>)}</article></section>}
  </main>;
}
function Empty({text}:{text:string}){return <div className="codex-empty"><b>∅</b><p>{text}</p></div>}
