"use client";
import{useEffect,useState}from"react";import{createClient}from"../../lib/supabase/client";
export type RoomHomunculus={id:string;user_id:string;character_id:string;name:string;stance:string;hp_current:number;hp_max:number;guard_points:number;active_table_id:string|null};
export type RoomHomunculusCommand={id:string;companion_id:string;command:string;response_th:string;created_at:string};
type Monster={id:string;name_th:string;hp_current:number;hp_max:number};type CombatAction={id:string;companion_id:string;action_type:"assist"|"guard";round_number:number;applied_damage:number;guard_points:number;effect_th:string;created_at:string};
export function HomunculusRoomPanel({tableId,currentUserId,readOnly,monsters:initialMonsters,initialCompanions,initialCommands}:{tableId:string;currentUserId:string;readOnly:boolean;monsters:Monster[];initialCompanions:RoomHomunculus[];initialCommands:RoomHomunculusCommand[]}){
  const[companions,setCompanions]=useState(initialCompanions);const[commands,setCommands]=useState(initialCommands);const[actions,setActions]=useState<CombatAction[]>([]);const[monsters,setMonsters]=useState(initialMonsters);const[target,setTarget]=useState(initialMonsters.find(item=>item.hp_current>0)?.id??"");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  useEffect(()=>{const supabase=createClient();void supabase.from("companion_combat_actions").select("*").eq("table_id",tableId).order("created_at",{ascending:false}).limit(12).then(({data})=>{if(data)setActions(data as CombatAction[])});const channel=supabase.channel(`homunculi-${tableId}`).on("postgres_changes",{event:"*",schema:"public",table:"homunculus_companions"},payload=>{const incoming=(payload.new??payload.old)as RoomHomunculus;if(payload.eventType==="DELETE"||incoming.active_table_id!==tableId)setCompanions(current=>current.filter(item=>item.id!==incoming.id));else setCompanions(current=>[incoming,...current.filter(item=>item.id!==incoming.id)]);}).on("postgres_changes",{event:"INSERT",schema:"public",table:"homunculus_commands",filter:`table_id=eq.${tableId}`},payload=>setCommands(current=>[payload.new as RoomHomunculusCommand,...current].slice(0,20))).on("postgres_changes",{event:"INSERT",schema:"public",table:"companion_combat_actions",filter:`table_id=eq.${tableId}`},payload=>setActions(current=>[payload.new as CombatAction,...current].slice(0,12))).on("postgres_changes",{event:"UPDATE",schema:"public",table:"generated_monsters",filter:`table_id=eq.${tableId}`},payload=>{const incoming=payload.new as Monster;setMonsters(current=>current.map(item=>item.id===incoming.id?incoming:item));}).subscribe();return()=>{void supabase.removeChannel(channel)}},[tableId]);
  async function combat(companionId:string,action:"assist"|"guard"){setBusy(true);setMessage("");try{const response=await fetch("/api/companions/combat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companionId,action,monsterId:action==="assist"?target:null})});const result=await response.json();if(!response.ok)throw new Error(result.error==="initiative_required"?"เริ่ม Initiative ก่อนสั่งเข้ารบ":result.error==="action_spent"?"โฮมุนครุสใช้ action ในรอบนี้แล้ว":"คำสั่งต่อสู้ไม่สำเร็จ");setActions(current=>[result.action,...current.filter(item=>item.id!==result.action.id)].slice(0,12));setCompanions(current=>current.map(item=>item.id===result.companion.id?result.companion:item));if(result.monster)setMonsters(current=>current.map(item=>item.id===result.monster.id?{...item,hp_current:result.monster.hp_current}:item));setMessage(result.action.effect_th);}catch(caught){setMessage(caught instanceof Error?caught.message:"คำสั่งต่อสู้ไม่สำเร็จ");}finally{setBusy(false)}}
  const living=monsters.filter(item=>item.hp_current>0);return <section className="room-homunculi"><header><div><small>BOUND COMPANIONS · ROUND-LIMITED COMBAT</small><h2>โฮมุนครุสในห้อง</h2></div><span>{companions.length} ACTIVE</span></header>{companions.length?<div>{companions.map(companion=><article key={companion.id}><b>{companion.name.slice(0,1)}</b><span><strong>{companion.name}</strong><small>{companion.stance} · {companion.hp_current}/{companion.hp_max} HP{companion.guard_points>0?` · GUARD ${companion.guard_points}`:""}</small></span>{companion.user_id===currentUserId&&!readOnly&&<div className="companion-combat"><select value={target} onChange={event=>setTarget(event.target.value)}><option value="">เลือกอสูร</option>{living.map(monster=><option value={monster.id} key={monster.id}>{monster.name_th} · {monster.hp_current} HP</option>)}</select><button disabled={busy||!target} onClick={()=>combat(companion.id,"assist")}>ช่วยโจมตี</button><button disabled={busy} onClick={()=>combat(companion.id,"guard")}>คุ้มกัน</button></div>}</article>)}</div>:<p>ยังไม่มีโฮมุนครุสถูกอัญเชิญเข้าห้อง</p>}{message&&<p className="companion-message">{message}</p>}{actions.length>0&&<aside className="companion-combat-log">{actions.map(item=><blockquote key={item.id}><b>ROUND {item.round_number} · {item.action_type.toUpperCase()}</b><span>{item.effect_th}{item.applied_damage?` · ${item.applied_damage} DAMAGE`:""}</span></blockquote>)}</aside>}{commands.length>0&&<aside>{commands.map(item=><blockquote key={item.id}><b>{item.command.toUpperCase()}</b><span>{item.response_th}</span></blockquote>)}</aside>}</section>}
