"use client";
import{useEffect,useMemo,useState}from"react";
import{createClient}from"../../lib/supabase/client";
import type{TimedCombatAction}from"../../lib/combat/types";
import type{CombatEnvironmentObject}from"../../lib/combat/environment";
import type{GeneratedMonster}from"../../lib/monsters/types";
import{MonsterWeaknessProbe}from"./monster-weakness-probe";

const gradeLabel={perfect:"PERFECT",good:"GOOD",weak:"WEAK",miss:"MISS"}as const;

function TimingAttack({monster,characterId,currentUserId,canAttack,actions,onAction,onHp}:{monster:GeneratedMonster;characterId:string|null;currentUserId:string;canAttack:boolean;actions:TimedCombatAction[];onAction:(action:TimedCombatAction)=>void;onHp:(hp:number)=>void}){
  const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[now,setNow]=useState(Date.now());const[clockOffset,setClockOffset]=useState(0);
  const pending=actions.find(item=>item.monster_id===monster.id&&item.actor_user_id===currentUserId&&item.status==="pending");
  const recent=actions.filter(item=>item.monster_id===monster.id&&item.status==="resolved").slice(0,4);
  useEffect(()=>{if(!pending)return;const timer=window.setInterval(()=>setNow(Date.now()),32);return()=>window.clearInterval(timer);},[pending]);
  const timing=useMemo(()=>{if(!pending)return null;const serverNow=now+clockOffset;const opens=new Date(pending.opens_at).getTime();const target=new Date(pending.target_at).getTime();const closes=new Date(pending.closes_at).getTime();return{progress:Math.max(0,Math.min(100,((serverNow-opens)/(closes-opens))*100)),target:((target-opens)/(closes-opens))*100,ready:serverNow>=opens,expired:serverNow>closes};},[pending,now,clockOffset]);
  async function send(action:"start"|"resolve"){
    setBusy(true);setMessage("");try{const supabase=createClient();if(action==="start"){const sentAt=Date.now();const{data,error}=await supabase.rpc("start_timed_attack_synced",{target_monster_id:monster.id,target_character_id:characterId});const receivedAt=Date.now();if(error||!data)throw error??new Error("start failed");setClockOffset(new Date(data.server_now).getTime()-(sentAt+receivedAt)/2);onAction(data.action as TimedCombatAction);}else{const pressedAt=new Date(Date.now()+clockOffset).toISOString();const{data,error}=await supabase.rpc("resolve_timed_attack_synced",{target_action_id:pending?.id,client_pressed_at:pressedAt});if(error||!data)throw error??new Error("resolve failed");onAction(data.action as TimedCombatAction);onHp(data.monster.hp_current);setMessage(`${gradeLabel[data.action.grade as keyof typeof gradeLabel]} · ${data.action.applied_damage} DAMAGE${data.action.weakness_effective?" · WEAKNESS!":""}`);}}catch(caught){const detail=caught instanceof Error?caught.message:String(caught);setMessage(detail.includes("attack pending")?"มีจังหวะโจมตีที่ยังไม่จบ":detail.includes("timing not open")?"ยังเร็วเกินไป รอให้แสงเข้าราง":"โจมตีไม่สำเร็จ");}finally{setBusy(false);}}
  return <div className="timing-combat">
    <div className="timing-title"><b>TIMING STRIKE</b><span>{pending?`จังหวะของ ${pending.character_name}`:"กดเริ่ม แล้วฟันเมื่อลูกแสงตรงรูนทอง"}</span></div>
    {pending&&timing?<><div className="timing-track"><i style={{left:`${timing.target}%`}}/><b style={{left:`${timing.progress}%`}}/></div><button className="timing-strike" disabled={busy||!timing.ready} onClick={()=>send("resolve")}>{timing.expired?"รับผลพลาด":timing.ready?"โจมตีตอนนี้!":"เตรียมตัว…"}</button></>:<button disabled={busy||!canAttack||!characterId||monster.hp_current<1} onClick={()=>send("start")}>{monster.hp_current<1?"อสูรถูกโค่นแล้ว":canAttack&&characterId?"เริ่มจับจังหวะ":"เชื่อมตัวละครเพื่อโจมตี"}</button>}
    {message&&<p>{message}</p>}
    {recent.length>0&&<div className="timing-history">{recent.map(item=><span className={item.grade??"miss"} key={item.id}><b>{item.character_name}</b> {gradeLabel[item.grade??"miss"]} · {item.applied_damage??0}</span>)}</div>}
  </div>;
}

export function MonsterForge({tableId,isDm,initialMonsters,currentUserId,characterId,canAttack}:{tableId:string;isDm:boolean;initialMonsters:GeneratedMonster[];currentUserId:string;characterId:string|null;canAttack:boolean}){
  const[monsters,setMonsters]=useState(initialMonsters);const[actions,setActions]=useState<TimedCombatAction[]>([]);const[objects,setObjects]=useState<CombatEnvironmentObject[]>([]);const[objectType,setObjectType]=useState("explosive_barrel");const[challenge,setChallenge]=useState("standard");const[biome,setBiome]=useState("forest");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  function mergeAction(incoming:TimedCombatAction){setActions(current=>[incoming,...current.filter(item=>item.id!==incoming.id)].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,40));}
  function mergeMonster(incoming:GeneratedMonster){setMonsters(current=>[incoming,...current.filter(item=>item.id!==incoming.id)].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,12));}
  function mergeObject(incoming:CombatEnvironmentObject){setObjects(current=>[incoming,...current.filter(item=>item.id!==incoming.id)].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,20));}
  useEffect(()=>{const supabase=createClient();void Promise.all([supabase.from("timed_combat_actions").select("*").eq("table_id",tableId).order("created_at",{ascending:false}).limit(40),supabase.from("combat_environment_objects").select("*").eq("table_id",tableId).order("created_at",{ascending:false}).limit(20)]).then(([combat,environment])=>{if(combat.data)setActions(combat.data as TimedCombatAction[]);if(environment.data)setObjects(environment.data as CombatEnvironmentObject[]);});const channel=supabase.channel(`combat-${tableId}`).on("postgres_changes",{event:"*",schema:"public",table:"generated_monsters",filter:`table_id=eq.${tableId}`},payload=>mergeMonster(payload.new as GeneratedMonster)).on("postgres_changes",{event:"*",schema:"public",table:"timed_combat_actions",filter:`table_id=eq.${tableId}`},payload=>mergeAction(payload.new as TimedCombatAction)).on("postgres_changes",{event:"*",schema:"public",table:"combat_environment_objects",filter:`table_id=eq.${tableId}`},payload=>mergeObject(payload.new as CombatEnvironmentObject)).subscribe();return()=>{void supabase.removeChannel(channel);};},[tableId]);
  async function generate(){setBusy(true);setMessage("");try{const response=await fetch("/api/monsters/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tableId,challenge,biome})});const result=await response.json();if(!response.ok)throw new Error(result.error==="cooldown"?"พลังสร้างอสูรยังไม่เสถียร รอ 10 วินาที":"สร้างอสูรไม่สำเร็จ");mergeMonster(result.monster);setMessage(`ปลุก ${result.monster.name_th} ขึ้นมาแล้ว`);}catch(caught){setMessage(caught instanceof Error?caught.message:"สร้างอสูรไม่สำเร็จ");}finally{setBusy(false);}}
  async function environment(payload:Record<string,string>){setBusy(true);setMessage("");try{const response=await fetch("/api/combat/environment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error==="object_spent"?"วัตถุนี้ถูกใช้ไปแล้ว":"ใช้สภาพแวดล้อมไม่สำเร็จ");if(payload.action==="spawn"){mergeObject(result.object);setMessage(`วาง ${result.object.name_th} ในสนามแล้ว`);}else{mergeObject(result.object);setMonsters(current=>current.map(item=>item.id===result.monster.id?{...item,hp_current:result.monster.hp_current}:item));setMessage(`${result.object.effect_th} · ${result.object.applied_damage} DAMAGE`);}}catch(caught){setMessage(caught instanceof Error?caught.message:"ใช้สภาพแวดล้อมไม่สำเร็จ");}finally{setBusy(false);}}
  const activeObjects=objects.filter(item=>item.status==="active");
  return <section className="monster-forge"><header><div><small>PROCEDURAL BESTIARY · REALTIME COMBAT</small><h2>สนามประลองอสูร</h2></div><span>{isDm?"DM CONTROL":"PARTY VIEW"}</span></header>{isDm&&<div className="monster-controls"><select value={challenge} onChange={event=>setChallenge(event.target.value)}><option value="minion">Minion</option><option value="standard">Standard</option><option value="elite">Elite</option><option value="boss">Boss</option></select><select value={biome} onChange={event=>setBiome(event.target.value)}><option value="forest">ป่า</option><option value="cave">ถ้ำ</option><option value="swamp">หนองน้ำ</option><option value="ruins">ซากโบราณ</option></select><button onClick={generate} disabled={busy}>{busy?"กำลังปลุก…":"สุ่มอสูร"}</button></div>}{isDm&&<div className="environment-builder"><select value={objectType} onChange={event=>setObjectType(event.target.value)}><option value="explosive_barrel">ถังดินเพลิง</option><option value="falling_pillar">เสาหินแตกร้าว</option><option value="snare_trap">กับดักโซ่หนาม</option></select><button disabled={busy||activeObjects.length>=6} onClick={()=>environment({action:"spawn",tableId,objectType})}>วางวัตถุในฉาก</button></div>}{objects.length>0&&<div className="environment-ledger">{objects.slice(0,6).map(item=><span className={item.status} key={item.id}><b>{item.name_th}</b>{item.status==="active"?`${item.base_damage} ${item.damage_type}`:`${item.applied_damage} DMG · ${item.effect_th}`}</span>)}</div>}{message&&<p className="monster-message">{message}</p>}<div className="monster-list">{monsters.length?monsters.map(monster=><article className={monster.challenge_tier} key={monster.id}><div><small>{monster.challenge_tier} · {monster.biome}</small><h3>{monster.name_th}</h3><span>{monster.traits?.signature??"สัญชาตญาณดิบ"}</span></div><dl><div className="monster-hp"><dt>HP</dt><dd>{monster.hp_current}/{monster.hp_max}</dd><i style={{width:`${(monster.hp_current/monster.hp_max)*100}%`}}/></div><div><dt>AC</dt><dd>{monster.armor_class}</dd></div><div><dt>ATK</dt><dd>+{monster.attack_bonus}</dd></div><div><dt>DMG</dt><dd>{monster.damage_dice}</dd></div></dl>{activeObjects.length>0&&<div className="environment-actions">{activeObjects.map(item=><button key={item.id} disabled={busy||!canAttack||!characterId||monster.hp_current<1} onClick={()=>environment({action:"trigger",objectId:item.id,monsterId:monster.id,characterId:characterId??""})}>ใช้ {item.name_th}</button>)}</div>}<TimingAttack monster={monster} characterId={characterId} currentUserId={currentUserId} canAttack={canAttack} actions={actions} onAction={mergeAction} onHp={hp=>setMonsters(current=>current.map(item=>item.id===monster.id?{...item,hp_current:hp}:item))}/>{isDm&&<MonsterWeaknessProbe monsterId={monster.id}/>}</article>):<div className="monster-empty">DM ยังไม่ได้สร้างอสูรสำหรับการเผชิญหน้าครั้งนี้</div>}</div></section>;
}
