"use client";
import { useEffect,useState } from "react";
import { createClient } from "../../lib/supabase/client";
import type { NpcDialogue } from "../../lib/npc/types";

const speakers=[["villager","ชาวบ้าน"],["merchant","พ่อค้า"],["guard","ทหารยาม"],["traveller","นักเดินทาง"],["innkeeper","เจ้าของโรงเตี๊ยม"],["scholar","นักปราชญ์"],["generic","ทั่วไป"]];
const contexts=[["greeting","ทักทาย"],["farewell","อำลา"],["shop","ร้านค้า"],["rumor","ข่าวลือ"],["quest","ภารกิจ"],["weather","อากาศ"],["danger","อันตราย"],["tavern","โรงเตี๊ยม"]];

export function NpcDialoguePanel({tableId,initialHistory}:{tableId:string;initialHistory:NpcDialogue[]}){
  const [history,setHistory]=useState(initialHistory);const [npcName,setNpcName]=useState("ผู้เฒ่าเอลริน");const [speakerType,setSpeakerType]=useState("villager");const [context,setContext]=useState("greeting");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{const supabase=createClient();const channel=supabase.channel(`npc-dialogue-${tableId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"npc_dialogue_history",filter:`table_id=eq.${tableId}`},payload=>{const incoming=payload.new as NpcDialogue;setHistory(current=>current.some(item=>item.id===incoming.id)?current:[...current.slice(-19),incoming]);}).subscribe();return()=>{void supabase.removeChannel(channel);};},[tableId]);
  async function speak(){setBusy(true);setError("");try{const response=await fetch("/api/npc/dialogue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tableId,npcName,speakerType,context})});const result=await response.json();if(!response.ok)throw new Error("เรียกบทสนทนาไม่สำเร็จ");const incoming=result.dialogue as NpcDialogue;setHistory(current=>current.some(item=>item.id===incoming.id)?current:[...current.slice(-19),incoming]);}catch(caught){setError(caught instanceof Error?caught.message:"เรียกบทสนทนาไม่สำเร็จ");}finally{setBusy(false);}}
  const latest=history.at(-1);return <section className="npc-dialogue"><header><div><small>WEIGHTED DIALOGUE</small><h2>สนทนากับ NPC</h2></div><span>{history.length} บทพูด</span></header><div className="npc-controls"><input maxLength={40} value={npcName} onChange={event=>setNpcName(event.target.value)} placeholder="ชื่อ NPC"/><select value={speakerType} onChange={event=>setSpeakerType(event.target.value)}>{speakers.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select value={context} onChange={event=>setContext(event.target.value)}>{contexts.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><button onClick={speak} disabled={busy||!npcName.trim()}>{busy?"…":"ให้ NPC พูด"}</button></div>{latest?<blockquote><b>{latest.npc_name}</b><p>“{latest.text_th}”</p><small>{latest.speaker_type} · {latest.context}</small></blockquote>:<div className="npc-empty">เลือกประเภทและสถานการณ์เพื่อเริ่มบทสนทนา</div>}{error&&<p className="dice-error">{error}</p>}<div className="npc-history">{[...history].reverse().slice(1,6).map(item=><span key={item.id}><b>{item.npc_name}</b>{item.text_th}</span>)}</div></section>;
}
