"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase/client";

export type AwarenessMember={user_id:string;display_name:string;role:string;character_id:string|null;character_name:string|null;location_id:number|null;location_name:string|null;awareness_tier:string};
export type MessengerDispatch={id:string;table_id:string;sender_user_id:string;recipient_user_id:string;sender_character_id:string;recipient_character_id:string;content:string;created_at:string};
const labels:Record<string,{title:string;detail:string}>={same_location:{title:"อยู่จุดเดียวกัน",detail:"มองเห็นและสื่อสารกันได้ทันที"},same_city:{title:"อยู่เมือง/ภูมิภาคเดียวกัน",detail:"รับรู้ตำแหน่งคร่าว ๆ ของกันและกัน"},far_city:{title:"อยู่คนละเมือง",detail:"ใช้ไอเทมนกสารเพื่อติดต่อ"},unknown:{title:"ไม่ทราบตำแหน่ง",detail:"สมาชิกยังไม่ได้ผูกตัวละคร"}};

export function PartyAwareness({tableId,viewerCharacterId,initialMembers,initialBirds,initialDispatches,canSend}:{tableId:string;viewerCharacterId:string;initialMembers:AwarenessMember[];initialBirds:number;initialDispatches:MessengerDispatch[];canSend:boolean}){
  const[members,setMembers]=useState(initialMembers);const[birds,setBirds]=useState(initialBirds);const[dispatches,setDispatches]=useState(initialDispatches);const[recipient,setRecipient]=useState("");const[content,setContent]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  const farMembers=useMemo(()=>members.filter(member=>member.character_id!==viewerCharacterId&&member.awareness_tier==="far_city"),[members,viewerCharacterId]);
  useEffect(()=>{if(!recipient&&farMembers[0])setRecipient(farMembers[0].user_id);},[farMembers,recipient]);
  useEffect(()=>{const refresh=async()=>{const response=await fetch(`/api/party/awareness?tableId=${tableId}&characterId=${viewerCharacterId}`);if(response.ok)setMembers((await response.json()).members);};const supabase=createClient();const channel=supabase.channel(`party-awareness-${tableId}`).on("postgres_changes",{event:"*",schema:"public",table:"character_world_positions"},()=>{void refresh();}).on("postgres_changes",{event:"INSERT",schema:"public",table:"messenger_dispatches",filter:`table_id=eq.${tableId}`},payload=>{const incoming=payload.new as MessengerDispatch;setDispatches(current=>current.some(item=>item.id===incoming.id)?current:[incoming,...current].slice(0,12));}).subscribe();return()=>{void supabase.removeChannel(channel);};},[tableId,viewerCharacterId]);
  async function sendBird(){if(!recipient||!content.trim())return;setBusy(true);setMessage("");try{const response=await fetch("/api/party/messenger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tableId,characterId:viewerCharacterId,recipientUserId:recipient,content})});const result=await response.json();if(!response.ok)throw new Error(result.error==="messenger_bird_required"?"ไม่มีนกสารในกระเป๋า":result.error==="far_city_required"?"ใช้ได้เฉพาะเพื่อนที่อยู่คนละเมือง":"ส่งนกสารไม่สำเร็จ");setBirds(result.birdsRemaining);setDispatches(current=>current.some(item=>item.id===result.dispatch.id)?current:[result.dispatch,...current].slice(0,12));setContent("");setMessage("ปล่อยนกสารออกเดินทางแล้ว");}catch(caught){setMessage(caught instanceof Error?caught.message:"ส่งนกสารไม่สำเร็จ");}finally{setBusy(false);}}
  const nameFor=(characterId:string)=>members.find(member=>member.character_id===characterId)?.character_name??"นักผจญภัย";
  return <section className="party-awareness"><header><div><small>PARTY SPLIT · LIVE</small><h2>ตำแหน่งของปาร์ตี้</h2></div><span>{members.length} LINKED</span></header><div>{members.map(member=>{const tier=labels[member.awareness_tier]??labels.unknown;return <article className={member.awareness_tier} key={member.user_id}><b>{(member.character_name??member.display_name).slice(0,1).toUpperCase()}</b><span><strong>{member.character_name??member.display_name}</strong><small>{member.location_name??"ยังไม่ทราบตำแหน่ง"} · {member.role.toUpperCase()}</small></span><i><em>{tier.title}</em>{tier.detail}</i></article>;})}</div>{canSend&&farMembers.length>0&&<aside className="messenger-compose"><header><span><small>SEALED MESSENGER RAVEN</small><strong>ส่งข่าวข้ามเมือง</strong></span><b>{birds} ตัว</b></header><div><select aria-label="ผู้รับนกสาร" value={recipient} onChange={event=>setRecipient(event.target.value)}>{farMembers.map(member=><option value={member.user_id} key={member.user_id}>{member.character_name??member.display_name}</option>)}</select><input maxLength={240} value={content} onChange={event=>setContent(event.target.value)} placeholder="เขียนข้อความไม่เกิน 240 ตัวอักษร"/><button onClick={sendBird} disabled={busy||birds<1||!content.trim()}>{busy?"กำลังส่ง…":"ส่งนกสาร"}</button></div>{birds<1&&<Link href={`/shop?character=${viewerCharacterId}`}>ซื้อนกสารที่ร้านค้า →</Link>}{message&&<p>{message}</p>}</aside>}{dispatches.length>0&&<aside className="messenger-history"><small>MESSENGER LOG</small>{dispatches.map(item=><blockquote key={item.id}><b>{nameFor(item.sender_character_id)} → {nameFor(item.recipient_character_id)}</b><span>{item.content}</span><time>{new Date(item.created_at).toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})}</time></blockquote>)}</aside>}</section>;
}
