"use client";
import{useCallback,useEffect,useState}from"react";import{createClient}from"../../lib/supabase/client";import type{CharacterSkill,SkillUse}from"../../lib/skills/types";
const actionLabel={action:"ACTION",bonus:"BONUS",reaction:"REACTION"};const rechargeLabel={at_will:"ใช้ได้เสมอ",short_rest:"พักสั้น",long_rest:"พักยาว"};
export function SkillPanel({tableId,characterId,isDm,readOnly,initialSkills,initialUses}:{tableId:string;characterId:string|null;isDm:boolean;readOnly:boolean;initialSkills:CharacterSkill[];initialUses:SkillUse[]}){const[skills,setSkills]=useState(initialSkills);const[uses,setUses]=useState(initialUses);const[busy,setBusy]=useState<number|string|null>(null);const[message,setMessage]=useState("");
 const reload=useCallback(async()=>{if(!characterId)return;const response=await fetch(`/api/skills?tableId=${tableId}&characterId=${characterId}`);if(response.ok){const body=await response.json();setSkills(body.skills);setUses(body.uses)}},[characterId,tableId]);
 useEffect(()=>{if(!characterId)return;const supabase=createClient();const channel=supabase.channel(`skills-${tableId}-${characterId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"skill_uses",filter:`table_id=eq.${tableId}`},payload=>{const incoming=payload.new as SkillUse;setUses(current=>current.some(item=>item.id===incoming.id)?current:[...current.slice(-19),incoming])}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"character_room_skills",filter:`table_id=eq.${tableId}`},()=>void reload()).subscribe();return()=>{void supabase.removeChannel(channel)}},[characterId,reload,tableId]);
 async function useSkill(skill:CharacterSkill){if(!characterId)return;setBusy(skill.id);setMessage("");try{const response=await fetch("/api/skills",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"use",tableId,characterId,skillId:skill.id})});const body=await response.json();if(!response.ok)throw new Error(body.error==="no_uses"?"สกิลนี้หมดจำนวนใช้แล้ว ต้องพักก่อน":"ใช้สกิลไม่สำเร็จ");setSkills(current=>current.map(item=>item.id===skill.id?{...item,uses_remaining:body.uses_remaining}:item));setUses(current=>current.some(item=>item.id===body.use.id)?current:[...current.slice(-19),body.use]);setMessage(body.use.effect_summary)}catch(error){setMessage(error instanceof Error?error.message:"ใช้สกิลไม่สำเร็จ")}finally{setBusy(null)}}
 async function rest(restType:"short_rest"|"long_rest"){setBusy(restType);setMessage("");try{const response=await fetch("/api/skills",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"rest",tableId,restType})});const body=await response.json();if(!response.ok)throw new Error("เฉพาะ DM เท่านั้นที่ประกาศพักได้");await reload();setMessage(`${restType==="short_rest"?"พักสั้น":"พักยาว"}สำเร็จ · ฟื้นจำนวนใช้ ${body.restored} สกิล`)}catch(error){setMessage(error instanceof Error?error.message:"พักไม่สำเร็จ")}finally{setBusy(null)}}
 return <section className="skill-panel"><header><div><small>CLASS ABILITIES · REAL-TIME</small><h2>สกิลตัวละคร</h2></div>{isDm&&!readOnly&&<nav><button disabled={busy!==null}onClick={()=>rest("short_rest")}>พักสั้น</button><button disabled={busy!==null}onClick={()=>rest("long_rest")}>พักยาว</button></nav>}</header>{characterId&&!readOnly?<div className="skill-grid">{skills.map(skill=><article className={skill.effect_type}key={skill.id}><header><span>{actionLabel[skill.action_type]}</span><i>{skill.max_uses===0?"∞":`${skill.uses_remaining}/${skill.max_uses}`}</i></header><h3>{skill.name_th}</h3><p>{skill.description_th}</p><footer><small>{skill.dice_count?`${skill.dice_count}d${skill.dice_sides} + ${skill.modifier_stat?.slice(0,3).toUpperCase()}`:"ไม่ทอยเต๋า"} · {rechargeLabel[skill.recharge]}</small><button disabled={busy!==null||skill.uses_remaining===0}onClick={()=>useSkill(skill)}>{busy===skill.id?"กำลังใช้…":"ใช้สกิล"}</button></footer></article>)}</div>:<p className="skill-message">โหมดผู้ชม · ดูการใช้สกิลของสมาชิกในห้องได้อย่างเดียว</p>}{message&&<p className="skill-message"aria-live="polite">{message}</p>}<aside><small>SKILL FEED · ทุกคนในห้องเห็นพร้อมกัน</small>{uses.length?[...uses].reverse().slice(0,8).map(item=><div key={item.id}><b>{item.roll_total??"✦"}</b><span><strong>{item.character_name} · {item.skill_name}</strong><small>{item.effect_summary}</small></span><time>{new Date(item.created_at).toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})}</time></div>):<p>ยังไม่มีการใช้สกิลในห้องนี้</p>}</aside></section>}
