"use client";
import{useEffect,useRef,useState}from"react";import type{Howl as HowlType}from"howler";
type SoundPrefs={music:number;effects:number;muted:boolean;track:"forest"|"tavern"|"arcane"};const defaults:SoundPrefs={music:.28,effects:.65,muted:false,track:"forest"};
function wavData(duration:number,sample:(time:number,index:number)=>number){const rate=8000,count=Math.floor(duration*rate),buffer=new ArrayBuffer(44+count*2),view=new DataView(buffer);const text=(offset:number,value:string)=>[...value].forEach((char,index)=>view.setUint8(offset+index,char.charCodeAt(0)));text(0,"RIFF");view.setUint32(4,36+count*2,true);text(8,"WAVEfmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,"data");view.setUint32(40,count*2,true);for(let i=0;i<count;i++)view.setInt16(44+i*2,Math.max(-1,Math.min(1,sample(i/rate,i)))*32767,true);const bytes=new Uint8Array(buffer);let binary="";for(let start=0;start<bytes.length;start+=8192)binary+=String.fromCharCode(...bytes.subarray(start,start+8192));return`data:audio/wav;base64,${btoa(binary)}`}
function ambient(track:SoundPrefs["track"]){const roots={forest:[110,164.81,220],tavern:[130.81,196,261.63],arcane:[98,146.83,233.08]}[track];return wavData(8,(time)=>{const fade=Math.min(1,time/.6,(8-time)/.6),pulse=.72+.18*Math.sin(Math.PI*time/4);return fade*pulse*(Math.sin(2*Math.PI*roots[0]*time)*.12+Math.sin(2*Math.PI*roots[1]*time)*.065+Math.sin(2*Math.PI*roots[2]*time)*.035)})}
function diceEffect(){return wavData(.72,(time,index)=>{const impacts=[0,.13,.27,.43,.57].reduce((sum,at)=>sum+(time>=at?Math.exp(-(time-at)*28):0),0);const noise=Math.sin(index*12.9898)*Math.sin(index*78.233);return noise*impacts*.34})}

export function SoundController(){const[open,setOpen]=useState(false);const[enabled,setEnabled]=useState(false);const[prefs,setPrefs]=useState<SoundPrefs>(defaults);const musicRef=useRef<HowlType|null>(null),effectRef=useRef<HowlType|null>(null);useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("mythweave-sound")??"null")as Partial<SoundPrefs>|null;if(saved)setPrefs({...defaults,...saved})}catch{}},[]);useEffect(()=>{const play=()=>{if(enabled&&!prefs.muted)effectRef.current?.play()};window.addEventListener("mythweave:dice-sfx",play);return()=>window.removeEventListener("mythweave:dice-sfx",play)},[enabled,prefs.muted]);function save(next:SoundPrefs){setPrefs(next);localStorage.setItem("mythweave-sound",JSON.stringify(next));musicRef.current?.volume(next.music);effectRef.current?.volume(next.effects);if(next.muted){musicRef.current?.mute(true);effectRef.current?.mute(true)}else{musicRef.current?.mute(false);effectRef.current?.mute(false)}}async function start(track=prefs.track){const{Howl}=await import("howler");musicRef.current?.unload();musicRef.current=new Howl({src:[ambient(track)],format:["wav"],loop:true,volume:prefs.music});if(!effectRef.current)effectRef.current=new Howl({src:[diceEffect()],format:["wav"],volume:prefs.effects});if(!prefs.muted)musicRef.current.play();setEnabled(true)}async function chooseTrack(track:SoundPrefs["track"]){save({...prefs,track});if(enabled)await start(track)}function toggleMute(){const next={...prefs,muted:!prefs.muted};save(next);if(!next.muted&&enabled&&!musicRef.current?.playing())musicRef.current?.play()}
 return <aside className={`sound-dock ${open?"open":""}`}><button className="sound-orb" aria-label="เปิดแผงควบคุมเสียง" onClick={()=>setOpen(value=>!value)}>{prefs.muted?"♩":"♫"}</button>{open&&<section><header><div><small>HOWLER AUDIO MIXER</small><h2>เสียงแห่งการผจญภัย</h2></div><button onClick={()=>setOpen(false)}>×</button></header>{!enabled?<button className="sound-start" onClick={()=>void start()}>เริ่มเสียงบรรยากาศ</button>:<button className="sound-mute" onClick={toggleMute}>{prefs.muted?"เปิดเสียง":"ปิดเสียงทั้งหมด"}</button>}<label>เพลงบรรยากาศ <b>{Math.round(prefs.music*100)}%</b></label><input aria-label="ระดับเสียงเพลง" type="range" min="0" max="1" step="0.01" value={prefs.music} onChange={event=>save({...prefs,music:Number(event.target.value)})}/><label>เอฟเฟกต์เต๋า <b>{Math.round(prefs.effects*100)}%</b></label><input aria-label="ระดับเสียงเอฟเฟกต์" type="range" min="0" max="1" step="0.01" value={prefs.effects} onChange={event=>save({...prefs,effects:Number(event.target.value)})}/><div className="sound-tracks">{(["forest","tavern","arcane"]as const).map(track=><button className={prefs.track===track?"selected":""} key={track} onClick={()=>void chooseTrack(track)}>{track==="forest"?"พงไพร":track==="tavern"?"โรงเตี๊ยม":"หอคอยเวท"}</button>)}</div><p>เบราว์เซอร์ต้องให้คุณกดเริ่มเสียงครั้งแรก · การตั้งค่าจะถูกจำอัตโนมัติ</p></section>}</aside>}
