"use client";

import Link from "next/link";
import { useState } from "react";

type Entry={id:string;monster_name:string;biome:string;signature_trait:string;encounter_count:number;notes:string;guessed_weakness:string|null;discovered_weakness:string|null;updated_at:string};
type Monster={id:string;name_th:string;biome:string;challenge_tier:string;traits:{signature?:string};created_at:string};
const damageTypes=[{id:"",label:"ยังไม่เดา"},{id:"fire",label:"ไฟ"},{id:"cold",label:"น้ำแข็ง"},{id:"lightning",label:"สายฟ้า"},{id:"radiant",label:"ศักดิ์สิทธิ์"},{id:"bludgeoning",label:"ทุบ"},{id:"piercing",label:"แทง"},{id:"slashing",label:"ฟัน"},{id:"poison",label:"พิษ"},{id:"psychic",label:"จิต"}];

export function BestiaryClient({character,initialEntries,monsters}:{character:{id:string;name:string};initialEntries:Entry[];monsters:Monster[]}){
  const[entries,setEntries]=useState(initialEntries);const[selected,setSelected]=useState(monsters[0]?.id??"");const[notes,setNotes]=useState("");const[guess,setGuess]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  async function record(){if(!selected)return;setBusy(true);setMessage("");try{const response=await fetch("/api/bestiary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({characterId:character.id,monsterId:selected,notes,guessedWeakness:guess||null})});const body=await response.json();if(!response.ok)throw new Error(body.error==="player_required"?"ตัวละครต้องอยู่ในห้องในฐานะ Player หรือ DM":"บันทึกไม่สำเร็จ");setEntries(current=>[body.entry,...current.filter(entry=>entry.id!==body.entry.id)]);setMessage(body.entry.discovered_weakness?"หลักฐานตรงกันแล้ว · ยืนยันจุดอ่อนสำเร็จ":body.entry.new_sighting?"เพิ่มการพบเห็นใหม่แล้ว":"อัปเดตบันทึกแล้ว · ตัวเดิมไม่นับเป็นการพบเห็นใหม่");}catch(caught){setMessage(caught instanceof Error?caught.message:"บันทึกไม่สำเร็จ");}finally{setBusy(false);}}
  return <main className="bestiary-shell"><header><Link href={`/characters/${character.id}`}>← Character Sheet</Link><span>MYTHWEAVE · FIELD BESTIARY</span><i>{character.name}</i></header><section className="bestiary-hero"><small>OBSERVE · RECORD · CONFIRM</small><h1>สมุดบันทึกอสูร</h1><p>บันทึกด้วยตนเอง · การพบตัวเดิมซ้ำไม่นับ · จุดอ่อนยืนยันเมื่อหลักฐานครบสองการเผชิญหน้า</p></section>{message&&<p className="bestiary-message">{message}</p>}<section className="bestiary-layout"><aside><small>AVAILABLE SIGHTINGS</small><h2>อสูรที่เคยพบในห้อง</h2>{monsters.length?monsters.map(monster=><button className={selected===monster.id?"selected":""} onClick={()=>{setSelected(monster.id);const entry=entries.find(item=>item.monster_name===monster.name_th);setNotes(entry?.notes??"");setGuess(entry?.guessed_weakness??"");}} key={monster.id}><b>{monster.name_th}</b><span>{monster.challenge_tier} · {monster.biome}</span></button>):<p>ยังไม่มีอสูรจากห้องที่คุณเข้าร่วม</p>}<label>ข้อสังเกต<textarea maxLength={1000} value={notes} onChange={event=>setNotes(event.target.value)} placeholder="พฤติกรรม ร่องรอย รูปแบบการโจมตี…"/></label><label>เดาจุดอ่อน<select value={guess} onChange={event=>setGuess(event.target.value)}>{damageTypes.map(type=><option value={type.id} key={type.id}>{type.label}</option>)}</select></label><button className="record-button" onClick={record} disabled={!selected||busy}>{busy?"กำลังจารึก…":"จารึกการพบเห็น"}</button></aside><div className="bestiary-entries">{entries.length?entries.map(entry=><article className={entry.discovered_weakness?"discovered":"unknown"} key={entry.id}><header><div><small>{entry.biome} · ENCOUNTERS {entry.encounter_count}</small><h2>{entry.monster_name}</h2><span>{entry.signature_trait}</span></div><b>{entry.discovered_weakness?"ยืนยันแล้ว":"ยังไม่ยืนยัน"}</b></header><p>{entry.notes||"ยังไม่มีข้อสังเกต"}</p><footer><span>เดา · {entry.guessed_weakness??"—"}</span><strong>{entry.discovered_weakness?`จุดอ่อน · ${entry.discovered_weakness}`:"ต้องพบอย่างน้อย 2 ตัวและเดาให้ถูก"}</strong></footer></article>):<div className="bestiary-empty">หน้ากระดาษยังว่าง · เลือกอสูรจากรายการเพื่อเริ่มจารึก</div>}</div></section></main>;
}
