"use client";

import { useMemo, useState } from "react";

type Entry={id:string;monster_name:string;biome:string;signature_trait:string;encounter_count:number;notes:string;discovered_weakness:string|null};
type Member={table_id:string;user_id:string;display_name:string;role:string;dice_tables:{code:string}|null};
type Share={id:string;entry_id:string;sender_user_id:string;share_mode:string;table_id:string|null;recipient_user_id:string|null;monster_name:string;biome:string;signature_trait:string;encounter_count:number;notes:string;discovered_weakness:string|null;created_at:string};
type Guild={id:number;name_th:string;emblem:string};
type Contribution={id:string;entry_id:string;guild_id:number;contribution_mode:string;payout_copper:number;affinity_delta:number;created_at:string};
type Destination={id:string;code?:string;name?:string};

export function BestiarySharingPanel({characterId,currentUserId,entries,members,initialShares,guilds,initialContributions}:{characterId:string;currentUserId:string;entries:Entry[];members:Member[];initialShares:Share[];guilds:Guild[];initialContributions:Contribution[]}){
  const rooms=useMemo(()=>[...new Map(members.map(member=>[member.table_id,{id:member.table_id,code:member.dice_tables?.code??member.table_id.slice(0,8)}])).values()],[members]);
  const recipients=useMemo(()=>[...new Map(members.filter(member=>member.user_id!==currentUserId).map(member=>[member.user_id,{id:member.user_id,name:member.display_name}])).values()],[members,currentUserId]);
  const[entryId,setEntryId]=useState(entries[0]?.id??"");const[mode,setMode]=useState<"party"|"direct"|"sell"|"donate">("party");const[target,setTarget]=useState(rooms[0]?.id??"");const[shares,setShares]=useState(initialShares);const[contributions,setContributions]=useState(initialContributions);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  const entry=entries.find(item=>item.id===entryId);const options:Destination[]=mode==="party"?rooms:mode==="direct"?recipients:guilds.map(guild=>({id:String(guild.id),name:guild.name_th}));
  function changeMode(next:typeof mode){setMode(next);const nextOptions=next==="party"?rooms:next==="direct"?recipients:guilds.map(guild=>({id:String(guild.id)}));setTarget(nextOptions[0]?.id??"");setMessage("");}
  async function submit(){if(!entry||!target)return;setBusy(true);setMessage("");try{const isGuild=mode==="sell"||mode==="donate";const response=await fetch("/api/bestiary/share",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(isGuild?{action:"guild",characterId,entryId:entry.id,guildId:Number(target),mode}:{action:"share",characterId,entryId:entry.id,mode,tableId:mode==="party"?target:null,recipientUserId:mode==="direct"?target:null})});const body=await response.json();if(!response.ok)throw new Error(body.error==="already_shared"?"ปลายทางนี้ได้รับบันทึกแล้ว":body.error==="knowledge_unconfirmed"?"กิลด์รับเฉพาะจุดอ่อนที่ยืนยันแล้ว":"ส่งบันทึกไม่สำเร็จ");if(isGuild){setContributions(current=>[{id:body.result.id,entry_id:entry.id,guild_id:Number(target),contribution_mode:mode,payout_copper:body.result.payout_copper,affinity_delta:body.result.affinity_delta,created_at:new Date().toISOString()},...current]);setMessage(mode==="sell"?`ขายข้อมูลสำเร็จ · +${body.result.payout_copper} CP · affinity +${body.result.affinity_delta}`:`บริจาคข้อมูลสำเร็จ · affinity +${body.result.affinity_delta}`);}else{setShares(current=>[{id:body.result.id,entry_id:entry.id,sender_user_id:currentUserId,share_mode:mode,table_id:mode==="party"?target:null,recipient_user_id:mode==="direct"?target:null,monster_name:entry.monster_name,biome:entry.biome,signature_trait:entry.signature_trait,encounter_count:entry.encounter_count,notes:entry.notes,discovered_weakness:entry.discovered_weakness,created_at:new Date().toISOString()},...current]);setMessage(mode==="party"?"แชร์ให้สมาชิกทั้งห้องแล้ว":"ส่งบันทึกให้ผู้เล่นแล้ว");}}catch(caught){setMessage(caught instanceof Error?caught.message:"ส่งบันทึกไม่สำเร็จ");}finally{setBusy(false);}}
  return <section className="bestiary-sharing"><header><div><small>KNOWLEDGE NETWORK</small><h2>แบ่งปันบันทึก</h2></div><span>ปาร์ตี้ · รายคน · กิลด์</span></header>{message&&<p className="sharing-message">{message}</p>}<div className="sharing-controls"><label>บันทึก<select value={entryId} onChange={event=>setEntryId(event.target.value)}>{entries.map(item=><option value={item.id} key={item.id}>{item.monster_name}</option>)}</select></label><label>วิธีส่ง<select value={mode} onChange={event=>changeMode(event.target.value as typeof mode)}><option value="party">แชร์ทั้งปาร์ตี้</option><option value="direct">ส่งให้ผู้เล่นคนเดียว</option><option value="sell">ขายให้กิลด์</option><option value="donate">บริจาคให้กิลด์</option></select></label><label>ปลายทาง<select value={target} onChange={event=>setTarget(event.target.value)}>{options.map(option=><option value={option.id} key={option.id}>{option.code?`ห้อง ${option.code}`:option.name??option.id}</option>)}</select></label><button onClick={submit} disabled={busy||!entry||!target||((mode==="sell"||mode==="donate")&&!entry.discovered_weakness)}>{busy?"กำลังส่ง…":mode==="sell"?"ขายข้อมูล":mode==="donate"?"บริจาคข้อมูล":"ส่งบันทึก"}</button></div>{(mode==="sell"||mode==="donate")&&entry&&!entry.discovered_weakness&&<p className="sharing-warning">ต้องยืนยันจุดอ่อนก่อน กิลด์จึงจะรับข้อมูล</p>}<div className="sharing-feed">{shares.map(share=><article key={share.id}><small>{share.share_mode==="party"?"PARTY SHARE":"DIRECT SHARE"}</small><h3>{share.monster_name}</h3><p>{share.notes||"ไม่มีหมายเหตุ"}</p><span>{share.discovered_weakness?`จุดอ่อน ${share.discovered_weakness}`:"ยังไม่ยืนยันจุดอ่อน"}</span></article>)}{contributions.map(item=>{const guild=guilds.find(value=>value.id===item.guild_id);return <article className="guild-share" key={item.id}><small>GUILD · {item.contribution_mode}</small><h3>{guild?.emblem} {guild?.name_th}</h3><p>{item.contribution_mode==="sell"?`รับ ${item.payout_copper} CP`:`บริจาคให้คลังความรู้`}</p><span>Affinity +{item.affinity_delta}</span></article>})}</div></section>;
}
