import{createBrowserClient}from"@supabase/ssr";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,appUrl=process.env.TEST_APP_URL??"http://127.0.0.1:3212";if(!url||!key)throw new Error("Missing Supabase environment");
const jar=new Map(),supabase=createBrowserClient(url,key,{cookies:{getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:items=>items.forEach(({name,value})=>value?jar.set(name,value):jar.delete(name))}});const suffix=crypto.randomUUID().replaceAll("-","");let characterId="";
const request=async(path,body,method="POST")=>{const response=await fetch(`${appUrl}${path}`,{method,headers:{"Content-Type":"application/json",Cookie:[...jar].map(([name,value])=>`${name}=${encodeURIComponent(value)}`).join("; ")},body:body?JSON.stringify(body):undefined});return{response,body:await response.json()}};
try{
 const{data,error}=await supabase.auth.signUp({email:`mythweave-combat-dm-${suffix}@example.com`,password:`Mythweave-${suffix}-9A`,options:{data:{display_name:"Hybrid DM Tester"}}});if(error||!data.session)throw error??new Error("No session");
 const{data:dimension}=await supabase.from("dimension_presets").select("id").eq("slug","aetherra-prime").single();const character=await request("/api/characters",{name:"Fortune Blade",race:"human",characterClass:"fighter",stats:{strength:14,dexterity:13,constitution:12,intelligence:10,wisdom:8,charisma:8},appearance:{skinTone:"warm",hairStyle:"short",hairColor:"raven",face:"sharp",body:"balanced"},dimensionId:dimension.id});if(character.response.status!==201)throw new Error("Character failed");characterId=character.body.id;
 const room=await request("/api/dice/tables",{action:"create",characterId,dmMode:"human"});const tableId=room.body.tableId;const monster=await request("/api/monsters/generate",{tableId,challenge:"boss",biome:"ruins"});if(monster.response.status!==201)throw new Error("Monster failed");
 const attack=await request("/api/combat/timing",{action:"start",monsterId:monster.body.monster.id,characterId});await new Promise(resolve=>setTimeout(resolve,Math.max(0,new Date(attack.body.combatAction.target_at).getTime()-Date.now())));const resolved=await request("/api/combat/timing",{action:"resolve",actionId:attack.body.combatAction.id,pressedAt:new Date().toISOString()});if(!resolved.response.ok)throw new Error("Attack failed");
 const{data:moments,error:momentError}=await supabase.from("combat_dm_moments").select("*").eq("action_id",attack.body.combatAction.id);if(momentError||moments?.length!==1||moments[0].status!=="pending")throw momentError??new Error("DM moment was not queued");
 const context=await request(`/api/dm/manual?tableId=${tableId}`,null,"GET");if(!context.response.ok||!context.body.prompt.includes("จังหวะที่รอ DM ตัดสิน")||!context.body.prompt.includes(moments[0].title_th))throw new Error("AI DM context missing combat cue");
 const{data:adjudicated,error:resolveError}=await supabase.rpc("resolve_combat_dm_moment",{target_moment_id:moments[0].id,target_resolution:"fortune"});if(resolveError||adjudicated.status!=="resolved"||adjudicated.resolution!=="fortune")throw resolveError??new Error("DM resolution failed");
 const{data:narrations}=await supabase.from("dm_narrations").select("narration").eq("table_id",tableId).order("created_at",{ascending:false}).limit(1);if(!narrations?.[0]?.narration.includes("โชคชะตา"))throw new Error("Resolution was not published");
 console.log(JSON.stringify({userId:data.user.id,hybridDm:true,pendingCue:true,aiContext:true,realtimeResolution:true,resolution:adjudicated.resolution}));
}finally{if(characterId)await supabase.from("characters").delete().eq("id",characterId)}
