import{createBrowserClient}from"@supabase/ssr";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,appUrl=process.env.TEST_APP_URL??"http://127.0.0.1:3212";if(!url||!key)throw new Error("Missing Supabase environment");
const jar=new Map(),supabase=createBrowserClient(url,key,{cookies:{getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:items=>items.forEach(({name,value})=>value?jar.set(name,value):jar.delete(name))}}),suffix=crypto.randomUUID().replaceAll("-","");let characterId="";
const request=async(path,body,method="POST")=>{const response=await fetch(`${appUrl}${path}`,{method,headers:{"Content-Type":"application/json",Cookie:[...jar].map(([name,value])=>`${name}=${encodeURIComponent(value)}`).join("; ")},body:body?JSON.stringify(body):undefined});return{response,body:await response.json()}};
try{
 const{data,error}=await supabase.auth.signUp({email:`mythweave-progression-${suffix}@example.com`,password:`Mythweave-${suffix}-9A`,options:{data:{display_name:"Rune Tester"}}});if(error||!data.session)throw error??new Error("No session");
 const{data:dimension}=await supabase.from("dimension_presets").select("id").eq("slug","aetherra-prime").single();
 const base={name:"Aster Runewright",race:"human",characterClass:"wizard",stats:{strength:8,dexterity:10,constitution:12,intelligence:14,wisdom:12,charisma:9},appearance:{skinTone:"warm",hairStyle:"short",hairColor:"raven",face:"sharp",body:"balanced"},dimensionId:dimension.id};
 const invalid=await request("/api/characters",{...base,name:"Bad Mix",secondaryClass:"barbarian",profession:"chef"});if(invalid.response.status!==400||invalid.body.error!=="invalid_calling")throw new Error("Incompatible multiclass was accepted");
 const created=await request("/api/characters",{...base,secondaryClass:"artificer",profession:"rune_scholar"});if(created.response.status!==201||created.body.starterSkills?.length!==4)throw new Error(`Multiclass creation failed ${JSON.stringify(created.body)}`);characterId=created.body.id;
 const[{data:calling},{data:languages},{data:runes},{data:learned},{data:blessingCatalog}]=await Promise.all([supabase.from("character_callings").select("*").eq("character_id",characterId).single(),supabase.from("character_languages").select("language_id,learned_via").eq("character_id",characterId),supabase.from("character_runes").select("rune_id,rune_definitions(language_id)").eq("character_id",characterId),supabase.from("character_skills").select("skill_id").eq("character_id",characterId),supabase.from("divine_blessing_definitions").select("tier")]);
 const runeDetails=runes?.[0]?.rune_definitions,runeLanguage=Array.isArray(runeDetails)?runeDetails[0]?.language_id:runeDetails?.language_id;if(calling?.secondary_class!=="artificer"||calling?.profession_id!=="rune_scholar"||!languages?.some(item=>item.language_id===runeLanguage&&item.learned_via==="formal_training")||learned?.length!==4)throw new Error("Calling or formally trained starter rune missing");if(new Set(blessingCatalog?.map(item=>item.tier)).size!==3)throw new Error("Divine blessing tiers missing");
 const fused=await request("/api/progression",{action:"fuse",characterId,firstSkillId:learned[0].skill_id,secondSkillId:learned[1].skill_id});if(fused.response.status!==201||!Number.isInteger(fused.body.result))throw new Error(`Fusion failed character=${characterId} ${JSON.stringify(fused.body)}`);
 const bind=await request("/api/progression",{action:"bind_rune",characterId,skillId:fused.body.result,runeId:runes[0].rune_id});if(bind.response.status!==201)throw new Error(`Rune bind failed ${JSON.stringify(bind.body)}`);
 const room=await request("/api/dice/tables",{action:"create",characterId,dmMode:"human"}),catalog=await request(`/api/skills?tableId=${room.body.tableId}&characterId=${characterId}`,null,"GET"),fusedSkill=catalog.body.skills?.find(skill=>skill.id===fused.body.result);if(!fusedSkill)throw new Error("Fused skill missing from combat catalog");
 const used=await request("/api/skills",{action:"use",tableId:room.body.tableId,characterId,skillId:fused.body.result});if(used.response.status!==201||!used.body.use?.effect_summary.includes("รูน"))throw new Error("Rune bonus missing from combat use");
 const page=await fetch(`${appUrl}/progression?character=${characterId}`,{headers:{Cookie:[...jar].map(([name,value])=>`${name}=${encodeURIComponent(value)}`).join("; ")}}),html=await page.text();if(!page.ok||!html.includes("SKILL FUSION")||!html.includes("RUNIC APPLICATION")||!html.includes("นักอักษรรูน"))throw new Error("Progression UI missing");
 const demo=await fetch(`${appUrl}/demo`),demoHtml=await demo.text();if(!demo.ok||!demoHtml.includes("REAL-TIME DICE")||!demoHtml.includes("ค้นพบก่อน จึงเรียนรู้")||!demoHtml.includes("TIMING COMBAT"))throw new Error("Public demo missing");
 console.log(JSON.stringify({userId:data.user.id,characterId,multiclass:true,profession:true,formalRuneTraining:true,fusedSkill:true,runeCombatBonus:true,blessingTiers:3,publicDemo:true,progressionUi:true}));
}finally{if(characterId)await supabase.from("characters").delete().eq("id",characterId)}
