import{createBrowserClient}from"@supabase/ssr";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,appUrl=process.env.TEST_APP_URL??"http://127.0.0.1:3212";if(!url||!key)throw new Error("Missing Supabase environment");
const jar=new Map();const supabase=createBrowserClient(url,key,{cookies:{getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:items=>items.forEach(({name,value})=>value?jar.set(name,value):jar.delete(name))}});const suffix=crypto.randomUUID().replaceAll("-","");const email=`mythweave-skill-${suffix}@example.com`;let characterId="",tableId="";
const request=async(path,body,method="POST")=>{const cookie=[...jar].map(([name,value])=>`${name}=${encodeURIComponent(value)}`).join("; ");const response=await fetch(`${appUrl}${path}`,{method,headers:{"Content-Type":"application/json",Cookie:cookie},body:body?JSON.stringify(body):undefined});return{response,body:await response.json()}};
try{const{data,error}=await supabase.auth.signUp({email,password:`Mythweave-${suffix}-9A`,options:{data:{display_name:"Skill Tester"}}});if(error||!data.session)throw error??new Error("No session");const{data:dimension,error:dimensionError}=await supabase.from("dimension_presets").select("id").eq("slug","aetherra-prime").single();if(dimensionError)throw dimensionError;
 const created=await request("/api/characters",{name:"Kara Ironwind",race:"human",characterClass:"fighter",stats:{strength:15,dexterity:13,constitution:14,intelligence:8,wisdom:10,charisma:12},appearance:{skinTone:"warm",hairStyle:"short",hairColor:"raven",face:"sharp",body:"balanced"},dimensionId:dimension.id});if(created.response.status!==201||created.body.starterItems?.length!==4||created.body.starterItems.some(item=>!item.content_items?.name_th)||created.body.starterSkills?.length!==3||created.body.starterSkills.some(skill=>!skill?.name_th))throw new Error(`Create character or starter loadout failed ${JSON.stringify(created.body)}`);characterId=created.body.id;
 const started=performance.now();const room=await request("/api/dice/tables",{action:"create",characterId});const roomMs=Math.round(performance.now()-started);if(room.response.status!==201)throw new Error(`Create room failed ${JSON.stringify(room.body)}`);tableId=room.body.tableId;
 const catalog=await request(`/api/skills?tableId=${tableId}&characterId=${characterId}`,null,"GET");if(!catalog.response.ok||catalog.body.skills?.length!==3)throw new Error(`Skill catalog failed ${JSON.stringify(catalog.body)}`);const wind=catalog.body.skills.find(skill=>skill.max_uses>0),strike=catalog.body.skills.find(skill=>skill.max_uses===0);if(!wind||!strike)throw new Error("Random starter skills did not include both charged and at-will skills");
 const first=await request("/api/skills",{action:"use",tableId,characterId,skillId:wind.id});if(first.response.status!==201||first.body.uses_remaining!==0)throw new Error("Charged skill did not decrement");const empty=await request("/api/skills",{action:"use",tableId,characterId,skillId:wind.id});if(empty.response.status!==409||empty.body.error!=="no_uses")throw new Error("Empty skill was usable");const atWill=await request("/api/skills",{action:"use",tableId,characterId,skillId:strike.id});if(atWill.response.status!==201||!Number.isInteger(atWill.body.use?.roll_total))throw new Error("At-will skill roll failed");
 const rested=await request("/api/skills",{action:"rest",tableId,restType:"short_rest"});if(!rested.response.ok)throw new Error("DM short rest failed");const afterRest=await request("/api/skills",{action:"use",tableId,characterId,skillId:wind.id});if(afterRest.response.status!==201)throw new Error("Skill did not recharge");const feed=await request(`/api/skills?tableId=${tableId}&characterId=${characterId}`,null,"GET");if(feed.body.uses?.length!==3)throw new Error("Realtime skill ledger did not persist");
 console.log(JSON.stringify({email,userId:data.user.id,characterId,tableId,roomCreateMs:roomMs,starterItems:created.body.starterItems.length,starterSkills:created.body.starterSkills.length,skillCatalog:catalog.body.skills.length,chargedSkill:true,emptyRejected:true,atWillRoll:true,shortRest:true,skillFeed:true}));
}finally{if(characterId)await supabase.from("characters").delete().eq("id",characterId);}
