alter table public.characters add column dimension_id uuid references public.dimension_presets(id);
update public.characters set dimension_id=(select id from public.dimension_presets where slug='aetherra-prime');
alter table public.characters alter column dimension_id set not null;
create index characters_dimension_idx on public.characters(user_id,dimension_id);
alter table public.dice_tables add column dimension_id uuid references public.dimension_presets(id);
update public.dice_tables set dimension_id=(select id from public.dimension_presets where slug='aetherra-prime');
alter table public.dice_tables alter column dimension_id set not null;
alter table public.room_saves add column dimension_id uuid references public.dimension_presets(id);
update public.room_saves save set dimension_id=room.dimension_id from public.dice_tables room where room.id=save.table_id;
alter table public.room_saves alter column dimension_id set not null;

create or replace function public.default_character_dimension()returns trigger language plpgsql security definer set search_path=''as $$begin if new.dimension_id is null then select id into new.dimension_id from public.dimension_presets where slug='aetherra-prime'and active;end if;if not exists(select 1 from public.dimension_presets where id=new.dimension_id and active)then raise exception'invalid dimension';end if;return new;end;$$;
create trigger characters_default_dimension before insert on public.characters for each row execute function public.default_character_dimension();
create or replace function public.enforce_room_dimension()returns trigger language plpgsql security definer set search_path=''as $$declare room_dimension uuid;hero_dimension uuid;begin select dimension_id into room_dimension from public.dice_tables where id=new.table_id;if new.character_id is not null then select dimension_id into hero_dimension from public.characters where id=new.character_id and user_id=new.user_id;if hero_dimension is null then raise exception'character not found';end if;if hero_dimension<>room_dimension then raise exception'dimension mismatch';end if;end if;return new;end;$$;
create trigger dice_members_same_dimension before insert or update of character_id,table_id on public.dice_table_members for each row execute function public.enforce_room_dimension();
create or replace function public.scope_room_save_dimension()returns trigger language plpgsql security definer set search_path=''as $$declare room_dimension uuid;begin select dimension_id into room_dimension from public.dice_tables where id=new.table_id;if room_dimension is null then raise exception'room not found';end if;if new.dimension_id is null then new.dimension_id:=room_dimension;end if;if new.dimension_id<>room_dimension then raise exception'dimension mismatch';end if;return new;end;$$;
create trigger room_saves_same_dimension before insert or update of table_id,dimension_id on public.room_saves for each row execute function public.scope_room_save_dimension();

create or replace function public.create_dimension_dice_table(member_name text,target_character_id uuid)returns table(table_id uuid,table_code text)language plpgsql security definer set search_path=''as $$declare created record;hero public.characters%rowtype;begin select*into hero from public.characters where id=target_character_id and user_id=auth.uid();if hero.id is null then raise exception'character not found';end if;select*into created from public.create_dice_table(member_name);update public.dice_tables set dimension_id=hero.dimension_id where id=created.table_id;perform public.link_dice_member_character(created.table_id,hero.id);return query select created.table_id,created.table_code;end;$$;
create or replace function public.join_dimension_dice_table(invite_code text,member_name text,requested_role text,target_character_id uuid)returns table(table_id uuid,table_code text)language plpgsql security definer set search_path=''as $$declare joined record;begin select*into joined from public.join_dice_table(invite_code,member_name,requested_role);if target_character_id is not null then perform public.link_dice_member_character(joined.table_id,target_character_id);end if;return query select joined.table_id,joined.table_code;end;$$;
revoke all on function public.create_dimension_dice_table(text,uuid)from public;revoke all on function public.join_dimension_dice_table(text,text,text,uuid)from public;grant execute on function public.create_dimension_dice_table(text,uuid)to authenticated;grant execute on function public.join_dimension_dice_table(text,text,text,uuid)to authenticated;
