alter table public.world_bosses add column enrage_stacks smallint not null default 0 check(enrage_stacks between 0 and 5);
alter table public.world_boss_contributions add column raw_damage integer not null default 0,add column cross_party_penalty_percent smallint not null default 0 check(cross_party_penalty_percent between 0 and 50);
update public.world_boss_contributions set raw_damage=damage where raw_damage=0;
create table public.world_boss_party_states(boss_id uuid not null references public.world_bosses(id)on delete cascade,table_id uuid not null references public.dice_tables(id)on delete cascade,status text not null default'active'check(status in('active','wiped')),reported_by uuid references auth.users(id),wiped_at timestamptz,updated_at timestamptz not null default now(),primary key(boss_id,table_id));
create table public.world_boss_raid_events(id uuid primary key default gen_random_uuid(),boss_id uuid not null references public.world_bosses(id)on delete cascade,source_table_id uuid not null references public.dice_tables(id)on delete cascade,event_type text not null check(event_type='party_wipe'),penalty_percent smallint not null default 10 check(penalty_percent between 1 and 25),effect_th text not null,created_at timestamptz not null default now(),expires_at timestamptz not null);
create index world_boss_raid_events_active_idx on public.world_boss_raid_events(boss_id,expires_at desc);
alter table public.world_boss_party_states enable row level security;alter table public.world_boss_raid_events enable row level security;
create policy "Room members can view their raid state"on public.world_boss_party_states for select to authenticated using(public.is_dice_table_member(table_id)or public.is_site_admin());
create policy "Authenticated players can view global raid events"on public.world_boss_raid_events for select to authenticated using(true);
create or replace function public.record_world_boss_party_wipe(target_boss_id uuid,target_table_id uuid)returns jsonb language plpgsql security definer set search_path=''as $$declare v_boss public.world_bosses%rowtype;v_event public.world_boss_raid_events%rowtype;v_stacks integer;begin if not exists(select 1 from public.dice_table_members where table_id=target_table_id and user_id=auth.uid()and role='dm')then raise exception'dm required';end if;select*into v_boss from public.world_bosses where id=target_boss_id for update;if v_boss.id is null then raise exception'boss not found';end if;if v_boss.status<>'active'then raise exception'boss inactive';end if;if exists(select 1 from public.world_boss_party_states where boss_id=v_boss.id and table_id=target_table_id and status='wiped')then raise exception'wipe already recorded';end if;insert into public.world_boss_party_states(boss_id,table_id,status,reported_by,wiped_at)values(v_boss.id,target_table_id,'wiped',auth.uid(),now())on conflict(boss_id,table_id)do update set status='wiped',reported_by=auth.uid(),wiped_at=now(),updated_at=now();insert into public.world_boss_raid_events(boss_id,source_table_id,event_type,effect_th,expires_at)values(v_boss.id,target_table_id,'party_wipe','เสียงคำรามจากปาร์ตี้ที่ล้มลงทำให้บอสคลุ้มคลั่ง ปาร์ตี้อื่นสร้างความเสียหายน้อยลง 10%',now()+interval'10 minutes')returning*into v_event;select least(5,count(*))into v_stacks from public.world_boss_raid_events where boss_id=v_boss.id and expires_at>now();update public.world_bosses set enrage_stacks=v_stacks,updated_at=now()where id=v_boss.id returning*into v_boss;return jsonb_build_object('boss',to_jsonb(v_boss),'event',to_jsonb(v_event));end;$$;
create or replace function public.strike_world_boss(target_boss_id uuid,target_table_id uuid,target_character_id uuid)
returns jsonb language plpgsql security definer set search_path=''as $$
declare v_boss public.world_bosses%rowtype;v_member public.dice_table_members%rowtype;v_hero public.characters%rowtype;v_contribution public.world_boss_contributions%rowtype;v_stat integer;v_raw integer;v_damage integer;v_penalty integer;v_hp bigint;v_phase smallint;v_stacks integer;
begin
  if not public.is_dice_table_actor(target_table_id)then raise exception'player required';end if;select*into v_member from public.dice_table_members where table_id=target_table_id and user_id=auth.uid()and character_id=target_character_id;if v_member.user_id is null then raise exception'character not linked';end if;select*into v_hero from public.characters where id=target_character_id and user_id=auth.uid();if v_hero.id is null then raise exception'character not found';end if;if v_hero.hp_current<1 then raise exception'character defeated';end if;
  select*into v_boss from public.world_bosses where id=target_boss_id for update;if v_boss.id is null then raise exception'boss not found';end if;if v_boss.status<>'active'or v_boss.ends_at<=now()or v_boss.hp_current<1 then raise exception'boss inactive';end if;if exists(select 1 from public.world_boss_contributions where boss_id=v_boss.id and character_id=v_hero.id and created_at>now()-interval'8 seconds')then raise exception'strike cooldown';end if;
  select least(50,coalesce(sum(penalty_percent),0)),least(5,count(*))into v_penalty,v_stacks from public.world_boss_raid_events where boss_id=v_boss.id and source_table_id<>target_table_id and expires_at>now();v_stat:=case v_hero.character_class when'fighter'then v_hero.strength when'ranger'then v_hero.dexterity when'wizard'then v_hero.intelligence when'cleric'then v_hero.wisdom when'rogue'then v_hero.dexterity when'paladin'then v_hero.charisma when'bard'then v_hero.charisma else v_hero.wisdom end;v_raw:=least(999,greatest(4,v_hero.level+floor(v_stat/3)::integer+4+floor(random()*7)::integer));v_damage:=greatest(1,floor(v_raw*(100-v_penalty)/100.0)::integer);v_damage:=least(v_damage,v_boss.hp_current::integer);v_hp:=v_boss.hp_current-v_damage;v_phase:=case when v_hp=0 then 5 when v_hp<=v_boss.hp_max/4 then 4 when v_hp<=v_boss.hp_max/2 then 3 when v_hp<=v_boss.hp_max*3/4 then 2 else 1 end;
  update public.world_bosses set hp_current=v_hp,phase=v_phase,enrage_stacks=v_stacks,status=case when v_hp=0 then'defeated'else'active'end,updated_at=now()where id=v_boss.id returning*into v_boss;insert into public.world_boss_contributions(boss_id,table_id,user_id,character_id,character_name,damage,raw_damage,cross_party_penalty_percent,boss_hp_after)values(v_boss.id,target_table_id,auth.uid(),v_hero.id,v_hero.name,v_damage,v_raw,v_penalty,v_hp)returning*into v_contribution;return jsonb_build_object('boss',to_jsonb(v_boss),'contribution',to_jsonb(v_contribution));
end;$$;
revoke all on function public.record_world_boss_party_wipe(uuid,uuid)from public;grant execute on function public.record_world_boss_party_wipe(uuid,uuid)to authenticated;
alter publication supabase_realtime add table public.world_boss_raid_events;
