create table public.achievement_definitions(id bigint generated always as identity primary key,slug text not null unique,name_th text not null,description_th text not null,condition_key text not null check(condition_key in('character_created','travel_count','craft_count','quest_count','forge_count','world_boss_hits')),target_value integer not null check(target_value>0),title_th text not null,icon text not null,sort_order smallint not null default 0,active boolean not null default true);
create table public.character_achievements(id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,achievement_id bigint not null references public.achievement_definitions(id),progress_value integer not null,unlocked_at timestamptz not null default now(),unique(character_id,achievement_id));
create table public.character_titles(character_id uuid primary key references public.characters(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,achievement_id bigint not null references public.achievement_definitions(id),equipped_at timestamptz not null default now());
alter table public.achievement_definitions enable row level security;alter table public.character_achievements enable row level security;alter table public.character_titles enable row level security;
create policy "Players read achievements"on public.achievement_definitions for select to authenticated using(active);create policy "Players read own unlocked achievements"on public.character_achievements for select to authenticated using(user_id=auth.uid());create policy "Players read own title"on public.character_titles for select to authenticated using(user_id=auth.uid());
insert into public.achievement_definitions(slug,name_th,description_th,condition_key,target_value,title_th,icon,sort_order)values
('first-thread','ด้ายเส้นแรก','สร้างตัวละครและเริ่มถักทอตำนาน','character_created',1,'ผู้เริ่มถักทอ','✦',1),('road-worn','รอยเท้าแห่งเอเธอร์รา','เดินทางสำเร็จ 5 ครั้ง','travel_count',5,'ผู้ท่องโลก','♞',2),('camp-artisan','ช่างฝีมือกองไฟ','ทำอาหารหรือปรุงยารวม 2 ครั้ง','craft_count',2,'มือแห่งเปลวไฟ','♨',3),('quest-bearer','ผู้รักษาคำสัตย์','ทำภารกิจสำเร็จ 3 งาน','quest_count',3,'ผู้รักษาคำสัตย์','◆',4),('relic-smith','ผู้ตีชะตา','สร้างไอเทมจาก Relic Forge 3 ชิ้น','forge_count',3,'ช่างตีชะตา','⚒',5),('worldscar','ผู้ฝากรอยแผล','โจมตี World Boss 5 ครั้ง','world_boss_hits',5,'ผู้สร้างรอยแผลโลก','⚔',6);
create or replace function public.claim_character_achievements(target_character_id uuid)returns jsonb language plpgsql security definer set search_path=''as $$declare hero public.characters%rowtype;definition public.achievement_definitions%rowtype;progress integer;new_ids bigint[]:='{}';begin select*into hero from public.characters where id=target_character_id and user_id=auth.uid();if hero.id is null then raise exception'character not found';end if;for definition in select*from public.achievement_definitions where active order by sort_order loop progress:=case definition.condition_key when'character_created'then 1 when'travel_count'then(select count(*)from public.character_travel_history where character_id=hero.id)when'craft_count'then(select count(*)from public.cooking_history where character_id=hero.id)+(select count(*)from public.brewing_history where character_id=hero.id)when'quest_count'then(select count(*)from public.character_quests where character_id=hero.id and status='completed')when'forge_count'then(select count(*)from public.generated_items where character_id=hero.id)when'world_boss_hits'then(select count(*)from public.world_boss_contributions where character_id=hero.id)else 0 end;if progress>=definition.target_value then insert into public.character_achievements(character_id,user_id,achievement_id,progress_value)values(hero.id,hero.user_id,definition.id,progress)on conflict do nothing;if found then new_ids:=array_append(new_ids,definition.id);end if;end if;end loop;return jsonb_build_object('new_achievement_ids',to_jsonb(new_ids),'new_count',cardinality(new_ids));end;$$;
create or replace function public.equip_character_title(target_character_id uuid,target_achievement_id bigint)returns public.character_titles language plpgsql security definer set search_path=''as $$declare result public.character_titles%rowtype;begin if not exists(select 1 from public.character_achievements where character_id=target_character_id and achievement_id=target_achievement_id and user_id=auth.uid())then raise exception'achievement locked';end if;insert into public.character_titles(character_id,user_id,achievement_id)values(target_character_id,auth.uid(),target_achievement_id)on conflict(character_id)do update set achievement_id=excluded.achievement_id,equipped_at=now()returning*into result;return result;end;$$;
revoke all on function public.claim_character_achievements(uuid)from public;revoke all on function public.equip_character_title(uuid,bigint)from public;grant execute on function public.claim_character_achievements(uuid)to authenticated;grant execute on function public.equip_character_title(uuid,bigint)to authenticated;
