alter table public.characters drop constraint characters_character_class_check;
alter table public.characters add constraint characters_character_class_check check(character_class in('fighter','ranger','wizard','cleric','rogue','paladin','bard','druid','barbarian','monk','sorcerer','warlock','artificer','necromancer'));
alter table public.skill_definitions drop constraint skill_definitions_class_id_check;
alter table public.skill_definitions add constraint skill_definitions_class_id_check check(class_id in('fighter','ranger','wizard','cleric','rogue','paladin','bard','druid','barbarian','monk','sorcerer','warlock','artificer','necromancer','fusion'));
alter table public.skill_definitions add column owner_character_id uuid references public.characters(id)on delete cascade;
alter table public.skill_definitions add column source_kind text not null default'class'check(source_kind in('class','fusion'));

insert into public.skill_definitions(slug,class_id,name_th,description_th,action_type,effect_type,dice_count,dice_sides,modifier_stat,max_uses,recharge,required_level,sort_order)values
('barbarian-rage','barbarian','คลั่งศึก','ปลุกแรงโทสะ เพิ่มพลังโจมตีและยืนหยัดต่อความเจ็บปวด','bonus','buff',0,null,'constitution',2,'long_rest',1,1),('barbarian-reckless','barbarian','ฟาดไม่คิดชีวิต','เปิดช่องป้องกันเพื่อแลกกับการโจมตีรุนแรง','action','damage',1,12,'strength',0,'at_will',1,2),('barbarian-roar','barbarian','คำรามข่มขวัญ','ทำลายกำลังใจของศัตรูรอบตัว','action','utility',1,6,'constitution',1,'short_rest',1,3),
('monk-flurry','monk','หมัดพายุ','รัวหมัดต่อเนื่องด้วยลมหายใจที่ควบคุม','bonus','damage',2,4,'dexterity',2,'short_rest',1,1),('monk-deflect','monk','ปัดวิถี','เบี่ยงการโจมตีที่พุ่งเข้าหาตนหรือสหาย','reaction','buff',1,6,'wisdom',2,'short_rest',1,2),('monk-step','monk','ย่างก้าวไร้น้ำหนัก','เคลื่อนผ่านสิ่งกีดขวางราวกับสายลม','bonus','utility',0,null,'dexterity',0,'at_will',1,3),
('sorcerer-chaos-bolt','sorcerer','ศรมนตราปั่นป่วน','ปล่อยเวทโดยสัญชาตญาณพร้อมธาตุที่แปรเปลี่ยน','action','damage',1,10,'charisma',0,'at_will',1,1),('sorcerer-twin-spell','sorcerer','มนตราสะท้อนคู่','ทำให้เวทถัดไปส่งผลต่ออีกหนึ่งเป้าหมาย','bonus','buff',0,null,'charisma',2,'long_rest',1,2),('sorcerer-wild-surge','sorcerer','คลื่นเวทไร้กรอบ','เสี่ยงปล่อยพลังดิบเพื่อสร้างผลเหนือคาด','action','damage',2,6,'charisma',1,'short_rest',1,3),
('warlock-eldritch','warlock','ลำแสงพันธสัญญา','ยิงพลังจากผู้มอบพันธสัญญา','action','damage',1,10,'charisma',0,'at_will',1,1),('warlock-hex','warlock','ตราคำสาป','ประทับตราให้เป้าหมายอ่อนแอต่อการโจมตี','bonus','buff',0,null,'charisma',2,'short_rest',1,2),('warlock-shadow-bargain','warlock','แลกเปลี่ยนกับเงา','รับพลังชั่วคราวโดยเปิดทางให้ผลข้างเคียง','reaction','utility',1,8,'charisma',1,'long_rest',1,3),
('artificer-arc-shot','artificer','กระสุนอาคม','ยิงอุปกรณ์เวทที่ประกอบขึ้นฉับพลัน','action','damage',1,8,'intelligence',0,'at_will',1,1),('artificer-turret','artificer','ป้อมกลจิ๋ว','กางกลไกช่วยกดดันพื้นที่ต่อสู้','action','buff',1,6,'intelligence',2,'long_rest',1,2),('artificer-repair','artificer','ซ่อมสนามรบ','ซ่อมเกราะ อุปกรณ์ หรือสิ่งแวดล้อมระหว่างฉาก','action','heal',1,8,'intelligence',2,'short_rest',1,3),
('necromancer-bone-spear','necromancer','หอกกระดูก','หล่อกระดูกวิญญาณเป็นหอกพุ่งใส่ศัตรู','action','damage',1,10,'intelligence',0,'at_will',1,1),('necromancer-life-thread','necromancer','ด้ายชีวิต','ดึงพลังตกค้างมาประคองผู้ใกล้ล้ม','reaction','heal',1,6,'intelligence',1,'short_rest',1,2),('necromancer-grave-whisper','necromancer','กระซิบสุสาน','ถามเศษความทรงจำจากวิญญาณในพื้นที่','action','utility',0,null,'wisdom',1,'long_rest',1,3)
on conflict(slug)do nothing;

create table public.multiclass_compatibility(primary_class text not null,secondary_class text not null,reason_th text not null,primary key(primary_class,secondary_class),check(primary_class<>secondary_class));
insert into public.multiclass_compatibility values
('fighter','barbarian','ใช้อาวุธและพละกำลังร่วมกัน'),('fighter','paladin','พื้นฐานเกราะและแนวหน้าสอดคล้องกัน'),('fighter','ranger','ต่อยอดความชำนาญอาวุธ'),('ranger','rogue','ความคล่องตัวและการซุ่มโจมตี'),('ranger','druid','ความรู้แดนเถื่อนและธรรมชาติ'),('wizard','artificer','ทฤษฎีเวทประยุกต์กับกลไก'),('wizard','necromancer','แตกแขนงศาสตร์อาคมต้องห้าม'),('cleric','paladin','พลังศรัทธาและการคุ้มครอง'),('cleric','druid','การเยียวยาและสมดุลชีวิต'),('rogue','bard','ไหวพริบ การแฝงตัว และเสน่ห์'),('paladin','warlock','พันธสัญญาที่ขัดแย้งแต่ทรงพลัง'),('bard','sorcerer','เวทจากตัวตนและการแสดงออก'),('druid','barbarian','สัญชาตญาณดิบและพลังธรรมชาติ'),('monk','rogue','การเคลื่อนไหวและจู่โจมแม่นยำ'),('monk','cleric','วินัยกายใจและศรัทธา'),('sorcerer','warlock','เวทโดยกำเนิดผสานพลังพันธสัญญา'),('artificer','rogue','เครื่องมือ กลไก และการแก้กับดัก'),('necromancer','warlock','ศาสตร์เงาและความรู้ต้องห้าม');
insert into public.multiclass_compatibility select secondary_class,primary_class,reason_th from public.multiclass_compatibility on conflict do nothing;
alter table public.multiclass_compatibility enable row level security;create policy "Players can read multiclass compatibility"on public.multiclass_compatibility for select to authenticated using(true);

create table public.profession_definitions(id text primary key,name_th text not null,icon text not null,description_th text not null,bonus_key text not null,bonus_label_th text not null,base_bonus_percent smallint not null default 5 check(base_bonus_percent between 5 and 10));
insert into public.profession_definitions values
('chef','เชฟ','♨','เชี่ยวชาญการปรุงอาหารและดึงคุณค่าจากวัตถุดิบ','cooking','โอกาสปรุงสำเร็จ',5),('chronicler','นักจดบันทึก','✎','บันทึกศัตรู ภาษา และเบาะแสได้แม่นยำ','lore','ค้นพบความรู้',5),('blacksmith','ช่างตีเหล็ก','⚒','อ่านเนื้อโลหะและเสริมอุปกรณ์ได้มั่นคง','upgrade','โอกาสตีบวก',5),('alchemist','นักเล่นแร่แปรธาตุ','⚗','ควบคุมปฏิกิริยาของยาและสารสกัด','brewing','โอกาสปรุงยา',5),('merchant','พ่อค้า','¤','ประเมินราคาและต่อรองโดยไม่เสียไมตรี','haggling','โอกาสต่อราคา',5),('scout','นักสอดแนม','⌖','อ่านเส้นทางและหลีกเลี่ยงภัยระหว่างเดินทาง','travel','ลดความเสี่ยงเดินทาง',5),('cartographer','นักทำแผนที่','⌑','มองเห็นเส้นทางลัดและจุดสำรวจที่ผู้อื่นพลาด','discovery','ค้นพบพื้นที่',5),('rune_scholar','นักอักษรรูน','ᚱ','ศึกษาภาษาโบราณและประยุกต์รูนกับสกิล','runes','ค้นพบและใช้รูน',5);
alter table public.profession_definitions enable row level security;create policy "Players can read professions"on public.profession_definitions for select to authenticated using(true);
create table public.character_callings(character_id uuid primary key references public.characters(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,secondary_class text,profession_id text not null references public.profession_definitions(id),profession_rank smallint not null default 1 check(profession_rank between 1 and 3),created_at timestamptz not null default now());
alter table public.character_callings enable row level security;create policy "Players can read their callings"on public.character_callings for select to authenticated using(user_id=auth.uid());

create table public.rune_languages(id text primary key,name_th text not null,rarity text not null,description_th text not null);
insert into public.rune_languages values('elder_futhark','อักษรรูนบรรพกาล','uncommon','ภาษาของช่างสลักยุคแรก'),('sylvan_glyph','อักขระพฤกษา','rare','รอยเขียนมีชีวิตของวิญญาณธรรมชาติ'),('abyssal_marks','ตราอเวจี','rare','สัญลักษณ์พันธสัญญาจากเบื้องล่าง');
alter table public.rune_languages enable row level security;create policy "Players can read rune languages"on public.rune_languages for select to authenticated using(true);
create table public.rune_definitions(id bigint generated always as identity primary key,slug text unique not null,name_th text not null,language_id text not null references public.rune_languages(id),effect_type text not null check(effect_type in('power','precision','ward','echo')),bonus_value smallint not null check(bonus_value between 1 and 3),description_th text not null,rarity text not null);
insert into public.rune_definitions(slug,name_th,language_id,effect_type,bonus_value,description_th,rarity)values('rune-ember','รูนเถ้าประกาย','elder_futhark','power',2,'เพิ่มผลทอยของสกิลโจมตี 2 แต้ม','uncommon'),('rune-keenedge','รูนคมสัจจะ','elder_futhark','precision',1,'เพิ่มความแม่นยำของสกิล 1 แต้ม','uncommon'),('rune-leafward','รูนใบไม้พิทักษ์','sylvan_glyph','ward',2,'เพิ่มผลทอยของสกิลรักษาหรือบัฟ 2 แต้ม','rare'),('rune-twinecho','รูนเสียงสะท้อนคู่','sylvan_glyph','echo',1,'เพิ่มผลทอยและทิ้งเสียงสะท้อนเวท','rare'),('rune-bloodmark','ตราโลหิตอเวจี','abyssal_marks','power',3,'เพิ่มผลทอย 3 แต้มแต่เปิดทางให้ DM สร้างผลข้างเคียง','rare');
alter table public.rune_definitions enable row level security;create policy "Players can read rune catalog"on public.rune_definitions for select to authenticated using(true);
create table public.character_languages(character_id uuid references public.characters(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,language_id text references public.rune_languages(id),learned_at timestamptz not null default now(),primary key(character_id,language_id));alter table public.character_languages enable row level security;create policy "Players can read their languages"on public.character_languages for select to authenticated using(user_id=auth.uid());
create table public.character_runes(character_id uuid references public.characters(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,rune_id bigint references public.rune_definitions(id),quantity smallint not null default 1 check(quantity between 1 and 20),found_at timestamptz not null default now(),primary key(character_id,rune_id));alter table public.character_runes enable row level security;create policy "Players can read their runes"on public.character_runes for select to authenticated using(user_id=auth.uid());
create table public.skill_rune_bindings(character_id uuid references public.characters(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,skill_id bigint references public.skill_definitions(id)on delete cascade,rune_id bigint references public.rune_definitions(id),bound_at timestamptz not null default now(),primary key(character_id,skill_id));alter table public.skill_rune_bindings enable row level security;create policy "Players can read their rune bindings"on public.skill_rune_bindings for select to authenticated using(user_id=auth.uid());
create table public.rune_searches(id uuid primary key default gen_random_uuid(),character_id uuid references public.characters(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,result_type text not null,result_name text,created_at timestamptz not null default now());alter table public.rune_searches enable row level security;create policy "Players can read their rune searches"on public.rune_searches for select to authenticated using(user_id=auth.uid());

create or replace function public.configure_character_calling(target_character_id uuid,target_secondary_class text,target_profession_id text)returns public.character_callings language plpgsql security definer set search_path=''as $$declare hero public.characters%rowtype;calling public.character_callings%rowtype;secondary_skill bigint;v_language text;rune bigint;begin
 select*into hero from public.characters where id=target_character_id and user_id=auth.uid();if hero.id is null then raise exception'character not found';end if;
 if not exists(select 1 from public.profession_definitions where id=target_profession_id)then raise exception'invalid profession';end if;
 if target_secondary_class is not null and not exists(select 1 from public.multiclass_compatibility where primary_class=hero.character_class and secondary_class=target_secondary_class)then raise exception'incompatible class';end if;
 insert into public.character_callings(character_id,user_id,secondary_class,profession_id)values(hero.id,auth.uid(),target_secondary_class,target_profession_id)returning*into calling;
 if target_secondary_class is not null then select id into secondary_skill from public.skill_definitions where class_id=target_secondary_class and required_level<=hero.level order by md5(hero.id::text||id::text)limit 1;insert into public.character_skills(character_id,user_id,skill_id)values(hero.id,auth.uid(),secondary_skill)on conflict do nothing;end if;
 if target_profession_id='rune_scholar'or mod(abs(pg_catalog.hashtext(hero.id::text)::bigint),100)<15 then select id into v_language from public.rune_languages order by md5(hero.id::text||id)limit 1;insert into public.character_languages values(hero.id,auth.uid(),v_language,now())on conflict do nothing;end if;
 if target_profession_id='rune_scholar'or mod(abs(pg_catalog.hashtext(reverse(hero.id::text))::bigint),100)<35 then select id into rune from public.rune_definitions where target_profession_id<>'rune_scholar'or language_id=v_language order by md5(id::text||hero.id::text)limit 1;insert into public.character_runes(character_id,user_id,rune_id,quantity)values(hero.id,auth.uid(),rune,1)on conflict do nothing;end if;
 return calling;end;$$;

insert into public.character_callings(character_id,user_id,profession_id)select id,user_id,case character_class when'wizard'then'chronicler'when'druid'then'alchemist'when'ranger'then'scout'when'fighter'then'blacksmith'else'merchant'end from public.characters on conflict do nothing;

create or replace function public.fuse_character_skills(target_character_id uuid,target_first_skill_id bigint,target_second_skill_id bigint)returns bigint language plpgsql security definer set search_path=''as $$declare hero public.characters%rowtype;a public.skill_definitions%rowtype;b public.skill_definitions%rowtype;new_id bigint;new_slug text;begin
 if target_first_skill_id=target_second_skill_id then raise exception'different skills required';end if;select*into hero from public.characters where id=target_character_id and user_id=auth.uid();if hero.id is null then raise exception'character not found';end if;if(select count(*)from public.skill_definitions where owner_character_id=hero.id)>=6 then raise exception'fusion limit';end if;
 select skill.*into a from public.skill_definitions skill join public.character_skills learned on learned.skill_id=skill.id where learned.character_id=hero.id and skill.id=target_first_skill_id;select skill.*into b from public.skill_definitions skill join public.character_skills learned on learned.skill_id=skill.id where learned.character_id=hero.id and skill.id=target_second_skill_id;if a.id is null or b.id is null then raise exception'skill unavailable';end if;
 select skill.id into new_id from public.skill_definitions skill join public.character_skills learned on learned.skill_id=skill.id where learned.character_id=hero.id and skill.source_kind='fusion'and skill.slug like'fusion-'||least(a.id,b.id)||'-'||greatest(a.id,b.id)||'-%'limit 1;if new_id is not null then return new_id;end if;
 new_slug:='fusion-'||least(a.id,b.id)||'-'||greatest(a.id,b.id)||'-'||replace(hero.id::text,'-','');insert into public.skill_definitions(slug,class_id,name_th,description_th,action_type,effect_type,dice_count,dice_sides,modifier_stat,max_uses,recharge,required_level,sort_order,owner_character_id,source_kind)values(new_slug,'fusion',a.name_th||' × '||b.name_th,'หลอมคุณสมบัติของ '||a.name_th||' และ '||b.name_th||' เป็นกระบวนท่าเฉพาะตัว','action',case when a.effect_type=b.effect_type then a.effect_type else'utility'end,greatest(1,least(3,greatest(a.dice_count,b.dice_count)+1)),greatest(coalesce(a.dice_sides,4),coalesce(b.dice_sides,4)),coalesce(a.modifier_stat,b.modifier_stat),1,'short_rest',1,90,hero.id,'fusion')returning id into new_id;insert into public.character_skills values(hero.id,auth.uid(),new_id,now());return new_id;end;$$;

create or replace function public.bind_skill_rune(target_character_id uuid,target_skill_id bigint,target_rune_id bigint)returns public.skill_rune_bindings language plpgsql security definer set search_path=''as $$declare rune public.rune_definitions%rowtype;binding public.skill_rune_bindings%rowtype;begin
 select definition.*into rune from public.rune_definitions definition join public.character_runes owned on owned.rune_id=definition.id where owned.character_id=target_character_id and owned.user_id=auth.uid()and definition.id=target_rune_id;if rune.id is null then raise exception'rune unavailable';end if;if not exists(select 1 from public.character_languages where character_id=target_character_id and user_id=auth.uid()and language_id=rune.language_id)then raise exception'language required';end if;if not exists(select 1 from public.character_skills where character_id=target_character_id and user_id=auth.uid()and skill_id=target_skill_id)then raise exception'skill unavailable';end if;insert into public.skill_rune_bindings(character_id,user_id,skill_id,rune_id)values(target_character_id,auth.uid(),target_skill_id,target_rune_id)on conflict(character_id,skill_id)do update set rune_id=excluded.rune_id,bound_at=now()returning*into binding;return binding;end;$$;

create or replace function public.search_rune_lore(target_character_id uuid)returns jsonb language plpgsql security definer set search_path=''as $$declare hero public.characters%rowtype;roll integer;found_language text;found_rune bigint;found_name text;begin select*into hero from public.characters where id=target_character_id and user_id=auth.uid();if hero.id is null then raise exception'character not found';end if;if exists(select 1 from public.rune_searches where character_id=hero.id and created_at>now()-interval'6 hours')then raise exception'search cooldown';end if;roll:=floor(random()*100)::integer;
 if roll<18 then select language.id,language.name_th into found_language,found_name from public.rune_languages language where not exists(select 1 from public.character_languages known where known.character_id=hero.id and known.language_id=language.id)order by random()limit 1;if found_language is not null then insert into public.character_languages values(hero.id,auth.uid(),found_language,now());end if;end if;
 if found_language is null and roll<55 then select rune.id,rune.name_th into found_rune,found_name from public.rune_definitions rune order by random()limit 1;insert into public.character_runes(character_id,user_id,rune_id,quantity)values(hero.id,auth.uid(),found_rune,1)on conflict(character_id,rune_id)do update set quantity=public.character_runes.quantity+1;end if;
 insert into public.rune_searches(character_id,user_id,result_type,result_name)values(hero.id,auth.uid(),case when found_language is not null then'language'when found_rune is not null then'rune'else'nothing'end,found_name);return jsonb_build_object('type',case when found_language is not null then'language'when found_rune is not null then'rune'else'nothing'end,'name',found_name,'roll',roll);end;$$;
create or replace function public.train_character_profession(target_character_id uuid)returns public.character_callings language plpgsql security definer set search_path=''as $$declare hero public.characters%rowtype;calling public.character_callings%rowtype;required_level integer;begin select*into hero from public.characters where id=target_character_id and user_id=auth.uid();select*into calling from public.character_callings where character_id=hero.id for update;if calling.character_id is null then raise exception'calling not found';end if;if calling.profession_rank>=3 then raise exception'max rank';end if;required_level:=case calling.profession_rank when 1 then 5 else 10 end;if hero.level<required_level then raise exception'level required';end if;update public.character_callings set profession_rank=profession_rank+1 where character_id=hero.id returning*into calling;return calling;end;$$;
revoke all on function public.configure_character_calling(uuid,text,text),public.fuse_character_skills(uuid,bigint,bigint),public.bind_skill_rune(uuid,bigint,bigint),public.search_rune_lore(uuid),public.train_character_profession(uuid)from public;grant execute on function public.configure_character_calling(uuid,text,text),public.fuse_character_skills(uuid,bigint,bigint),public.bind_skill_rune(uuid,bigint,bigint),public.search_rune_lore(uuid),public.train_character_profession(uuid)to authenticated;

create or replace function public.use_character_skill(target_table_id uuid,target_character_id uuid,target_skill_id bigint)
returns jsonb language plpgsql security definer set search_path=''as $$declare hero public.characters%rowtype;skill public.skill_definitions%rowtype;skill_state public.character_room_skills%rowtype;skill_use public.skill_uses%rowtype;rune public.rune_definitions%rowtype;roll_value integer:=0;modifier_value integer:=0;remaining smallint;summary text;begin
 if not public.is_dice_table_actor(target_table_id)then raise exception'actor required';end if;select*into hero from public.characters where id=target_character_id and user_id=auth.uid();if hero.id is null then raise exception'character not found';end if;if not exists(select 1 from public.dice_table_members where table_id=target_table_id and user_id=auth.uid()and character_id=hero.id and role in('player','dm'))then raise exception'character not in room';end if;select skill_definitions.*into skill from public.skill_definitions join public.character_skills learned on learned.skill_id=skill_definitions.id and learned.character_id=hero.id where skill_definitions.id=target_skill_id;if skill.id is null then raise exception'skill unavailable';end if;
 if skill.max_uses>0 then insert into public.character_room_skills(table_id,character_id,skill_id,uses_remaining)values(target_table_id,hero.id,skill.id,skill.max_uses)on conflict do nothing;update public.character_room_skills set uses_remaining=uses_remaining-1,updated_at=now()where table_id=target_table_id and character_id=hero.id and skill_id=skill.id and uses_remaining>0 returning*into skill_state;if skill_state.skill_id is null then raise exception'no uses remaining';end if;remaining:=skill_state.uses_remaining;end if;
 select definition.*into rune from public.skill_rune_bindings binding join public.rune_definitions definition on definition.id=binding.rune_id where binding.character_id=hero.id and binding.skill_id=skill.id;modifier_value:=case skill.modifier_stat when'strength'then floor((hero.strength-10)/2.0)when'dexterity'then floor((hero.dexterity-10)/2.0)when'constitution'then floor((hero.constitution-10)/2.0)when'intelligence'then floor((hero.intelligence-10)/2.0)when'wisdom'then floor((hero.wisdom-10)/2.0)when'charisma'then floor((hero.charisma-10)/2.0)else 0 end;
 if skill.dice_count>0 then for die in 1..skill.dice_count loop roll_value:=roll_value+floor(random()*skill.dice_sides)::integer+1;end loop;roll_value:=greatest(0,roll_value+modifier_value+coalesce(rune.bonus_value,0));summary:=skill.name_th||' · '||skill.dice_count||'d'||skill.dice_sides||case when modifier_value>=0 then' + 'else' - 'end||abs(modifier_value)||case when rune.id is not null then' + รูน '||rune.bonus_value else''end||' = '||roll_value;else summary:=skill.name_th||' · เปิดใช้ผลของสกิลแล้ว'||case when rune.id is not null then' · '||rune.name_th else''end;end if;
 insert into public.skill_uses(table_id,character_id,user_id,skill_id,character_name,skill_name,effect_type,roll_total,effect_summary)values(target_table_id,hero.id,auth.uid(),skill.id,hero.name,skill.name_th,skill.effect_type,case when skill.dice_count>0 then roll_value else null end,summary)returning*into skill_use;return jsonb_build_object('use',to_jsonb(skill_use),'uses_remaining',remaining);end;$$;

create or replace function public.cook_recipe(target_character_id uuid,target_recipe_id bigint)
returns jsonb language plpgsql security definer set search_path=''as $$declare hero public.characters%rowtype;recipe public.cooking_recipes%rowtype;ingredient record;stack public.character_item_stacks%rowtype;output public.content_items%rowtype;effect public.status_effect_templates%rowtype;rolled integer;modifier integer;profession_bonus integer:=0;passed boolean;history public.cooking_history%rowtype;begin
 select*into hero from public.characters where id=target_character_id and user_id=auth.uid();if hero.id is null then raise exception'character not found';end if;select*into recipe from public.cooking_recipes where id=target_recipe_id and active;if recipe.id is null then raise exception'recipe not found';end if;for ingredient in select*from public.cooking_recipe_ingredients where recipe_id=recipe.id loop select*into stack from public.character_item_stacks where character_id=target_character_id and user_id=auth.uid()and content_item_id=ingredient.content_item_id for update;if stack.id is null or stack.quantity<ingredient.quantity then raise exception'missing ingredients';end if;end loop;for ingredient in select*from public.cooking_recipe_ingredients where recipe_id=recipe.id loop delete from public.character_item_stacks where character_id=target_character_id and user_id=auth.uid()and content_item_id=ingredient.content_item_id and quantity=ingredient.quantity;update public.character_item_stacks set quantity=quantity-ingredient.quantity,updated_at=now()where character_id=target_character_id and user_id=auth.uid()and content_item_id=ingredient.content_item_id and quantity>ingredient.quantity;end loop;
 rolled:=floor(random()*20)::integer+1;modifier:=floor((hero.wisdom-10)::numeric/2)::integer;select case rank when 1 then 1 else 2 end into profession_bonus from(select profession_rank rank from public.character_callings where character_id=hero.id and profession_id='chef')x;profession_bonus:=coalesce(profession_bonus,0);passed:=rolled<>1 and rolled+modifier+profession_bonus>=recipe.difficulty_class;select*into output from public.content_items where id=recipe.output_item_id;if passed then insert into public.character_item_stacks(character_id,user_id,content_item_id,quantity,acquired_unit_value)values(target_character_id,auth.uid(),output.id,recipe.output_quantity,output.base_value)on conflict on constraint character_item_stacks_character_id_content_item_id_key do update set quantity=public.character_item_stacks.quantity+excluded.quantity,updated_at=now();if recipe.effect_template_id is not null then select*into effect from public.status_effect_templates where id=recipe.effect_template_id;insert into public.character_status_effects(character_id,user_id,template_id,name_th,effect_type,description_th,duration_remaining,stacks,modifiers,source)values(target_character_id,auth.uid(),effect.id,effect.name_th,effect.effect_type,effect.description_th,effect.default_duration,1,effect.modifiers,'อาหาร: '||recipe.name_th)on conflict on constraint character_status_effects_character_id_template_id_key do update set duration_remaining=effect.default_duration,source=excluded.source;end if;end if;insert into public.cooking_history(character_id,user_id,recipe_id,dice_roll,wisdom_modifier,difficulty_class,success)values(target_character_id,auth.uid(),recipe.id,rolled,modifier+profession_bonus,recipe.difficulty_class,passed)returning*into history;return jsonb_build_object('history_id',history.id,'recipe_id',recipe.id,'recipe_name',recipe.name_th,'dice_roll',rolled,'wisdom_modifier',modifier,'profession_bonus',profession_bonus,'profession_bonus_percent',profession_bonus*5,'total',rolled+modifier+profession_bonus,'difficulty_class',recipe.difficulty_class,'success',passed,'output_item_id',case when passed then output.id else null end,'output_name',case when passed then output.name_th else null end,'output_quantity',case when passed then recipe.output_quantity else 0 end);end;$$;
