create table public.solo_adventures(
  id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,
  status text not null default'active'check(status in('active','ended')),started_location_id bigint not null references public.world_locations(id),started_at timestamptz not null default now(),ended_at timestamptz,
  check((status='active'and ended_at is null)or(status='ended'and ended_at is not null))
);
create unique index one_active_solo_per_user on public.solo_adventures(user_id)where status='active';create index solo_character_idx on public.solo_adventures(character_id,started_at desc);
alter table public.solo_adventures enable row level security;create policy "Players can read their solo adventures"on public.solo_adventures for select to authenticated using(user_id=auth.uid());
create or replace function public.user_has_active_solo()returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.solo_adventures where user_id=(select auth.uid())and status='active')$$;
create or replace function public.is_dice_table_member(target_table_id uuid)returns boolean language sql stable security definer set search_path=''as $$select not public.user_has_active_solo()and exists(select 1 from public.dice_table_members where table_id=target_table_id and user_id=(select auth.uid()))$$;
create or replace function public.prevent_solo_room_membership()returns trigger language plpgsql security definer set search_path=''as $$begin if exists(select 1 from public.solo_adventures where user_id=new.user_id and status='active')then raise exception'solo mode forbids rooms';end if;return new;end;$$;
create trigger dice_members_block_solo before insert or update on public.dice_table_members for each row execute function public.prevent_solo_room_membership();
create or replace function public.enforce_solo_wilderness()returns trigger language plpgsql security definer set search_path=''as $$declare destination_type text;begin if exists(select 1 from public.solo_adventures where character_id=new.character_id and status='active')then select location_type into destination_type from public.world_locations where id=new.location_id;if destination_type<>'wilderness'then raise exception'solo wilderness only';end if;end if;return new;end;$$;
create trigger world_positions_solo_wilderness before insert or update of location_id on public.character_world_positions for each row execute function public.enforce_solo_wilderness();
create or replace function public.prevent_solo_magic_item()returns trigger language plpgsql security definer set search_path=''as $$begin if exists(select 1 from public.solo_adventures where character_id=new.character_id and status='active')then raise exception'solo magic disabled';end if;return new;end;$$;
create trigger generated_items_block_solo before insert on public.generated_items for each row execute function public.prevent_solo_magic_item();
create or replace function public.begin_solo_adventure(target_character_id uuid)returns jsonb language plpgsql security definer set search_path=''as $$declare hero public.characters%rowtype;position public.character_world_positions%rowtype;location public.world_locations%rowtype;session public.solo_adventures%rowtype;begin select*into hero from public.characters where id=target_character_id and user_id=auth.uid();if hero.id is null then raise exception'character not found';end if;if public.user_has_active_solo()then raise exception'solo already active';end if;if exists(select 1 from public.character_journeys where character_id=hero.id and status in('travelling','encounter'))then raise exception'journey active';end if;select*into position from public.character_world_positions where character_id=hero.id;if position.character_id is null then perform public.ensure_character_world_position(hero.id);select*into position from public.character_world_positions where character_id=hero.id;end if;select*into location from public.world_locations where id=position.location_id;if location.location_type<>'wilderness'then raise exception'wilderness required';end if;update public.homunculus_companions set active_table_id=null,stance='waiting',updated_at=now()where character_id=hero.id;insert into public.solo_adventures(character_id,user_id,started_location_id)values(hero.id,auth.uid(),location.id)returning*into session;return jsonb_build_object('id',session.id,'character_id',hero.id,'status',session.status,'location_id',location.id,'location_name',location.name_th,'started_at',session.started_at,'restrictions',jsonb_build_array('wilderness_only','no_magic_drops','no_rooms','no_dm'));end;$$;
create or replace function public.end_solo_adventure(target_character_id uuid)returns jsonb language plpgsql security definer set search_path=''as $$declare session public.solo_adventures%rowtype;begin update public.solo_adventures set status='ended',ended_at=now()where character_id=target_character_id and user_id=auth.uid()and status='active'returning*into session;if session.id is null then raise exception'solo not active';end if;return jsonb_build_object('id',session.id,'character_id',session.character_id,'status',session.status,'ended_at',session.ended_at);end;$$;
revoke all on function public.user_has_active_solo()from public;grant execute on function public.user_has_active_solo()to authenticated;
revoke all on function public.begin_solo_adventure(uuid)from public;revoke all on function public.end_solo_adventure(uuid)from public;grant execute on function public.begin_solo_adventure(uuid)to authenticated;grant execute on function public.end_solo_adventure(uuid)to authenticated;
