create table public.player_trade_offers(
  id uuid primary key default gen_random_uuid(),party_id uuid not null references public.persistent_parties(id)on delete cascade,
  sender_user_id uuid not null references auth.users(id)on delete cascade,sender_character_id uuid not null references public.characters(id)on delete cascade,
  recipient_user_id uuid not null references auth.users(id)on delete cascade,recipient_character_id uuid not null references public.characters(id)on delete cascade,
  offered_item_id bigint references public.content_items(id),offered_quantity integer not null default 0 check(offered_quantity between 0 and 99),offered_copper integer not null default 0 check(offered_copper between 0 and 1000000),
  requested_item_id bigint references public.content_items(id),requested_quantity integer not null default 0 check(requested_quantity between 0 and 99),requested_copper integer not null default 0 check(requested_copper between 0 and 1000000),
  status text not null default'pending'check(status in('pending','accepted','rejected','canceled','expired')),expires_at timestamptz not null default(now()+interval'24 hours'),created_at timestamptz not null default now(),resolved_at timestamptz,
  check(sender_character_id<>recipient_character_id),check(offered_quantity>0 or offered_copper>0),check((offered_item_id is null)=(offered_quantity=0)),check((requested_item_id is null)=(requested_quantity=0))
);
create index player_trade_participants_idx on public.player_trade_offers(sender_user_id,recipient_user_id,created_at desc);
alter table public.player_trade_offers enable row level security;create policy "Trade participants can read offers"on public.player_trade_offers for select to authenticated using(sender_user_id=auth.uid()or recipient_user_id=auth.uid());

create or replace function public.create_player_trade_offer(target_sender_character_id uuid,target_recipient_character_id uuid,target_offered_item_id bigint,target_offered_quantity integer,target_offered_copper integer,target_requested_item_id bigint,target_requested_quantity integer,target_requested_copper integer)returns public.player_trade_offers language plpgsql security definer set search_path=''as $$
declare sender_member public.persistent_party_members%rowtype;recipient_member public.persistent_party_members%rowtype;sender_wallet public.character_wallets%rowtype;sender_stack public.character_item_stacks%rowtype;item public.content_items%rowtype;offer public.player_trade_offers%rowtype;
begin
  if coalesce(target_offered_quantity,0)not between 0 and 99 or coalesce(target_requested_quantity,0)not between 0 and 99 or coalesce(target_offered_copper,0)not between 0 and 1000000 or coalesce(target_requested_copper,0)not between 0 and 1000000 then raise exception'invalid trade amount';end if;
  if coalesce(target_offered_quantity,0)=0 and coalesce(target_offered_copper,0)=0 then raise exception'empty offer';end if;
  select member.*into sender_member from public.persistent_party_members member join public.characters hero on hero.id=member.character_id where member.character_id=target_sender_character_id and member.user_id=auth.uid()and not exists(select 1 from public.character_life_profiles where character_id=hero.id and status<>'alive');
  if sender_member.id is null then raise exception'sender not found';end if;
  select*into recipient_member from public.persistent_party_members where character_id=target_recipient_character_id and party_id=sender_member.party_id;if recipient_member.id is null or recipient_member.user_id=auth.uid()then raise exception'recipient not found';end if;
  select*into sender_wallet from public.character_wallets where character_id=target_sender_character_id;if sender_wallet.balance_copper<coalesce(target_offered_copper,0)then raise exception'insufficient funds';end if;
  if coalesce(target_offered_quantity,0)>0 then select*into item from public.content_items where id=target_offered_item_id;if item.id is null then raise exception'item not found';end if;if item.rarity='soulbound'or coalesce((item.properties->>'tradeable')::boolean,true)=false then raise exception'soulbound item';end if;select*into sender_stack from public.character_item_stacks where character_id=target_sender_character_id and content_item_id=item.id;if sender_stack.id is null or sender_stack.quantity<target_offered_quantity then raise exception'insufficient items';end if;elsif target_offered_item_id is not null then raise exception'invalid trade item';end if;
  if coalesce(target_requested_quantity,0)>0 then select*into item from public.content_items where id=target_requested_item_id;if item.id is null then raise exception'item not found';end if;if item.rarity='soulbound'or coalesce((item.properties->>'tradeable')::boolean,true)=false then raise exception'soulbound item';end if;elsif target_requested_item_id is not null then raise exception'invalid trade item';end if;
  insert into public.player_trade_offers(party_id,sender_user_id,sender_character_id,recipient_user_id,recipient_character_id,offered_item_id,offered_quantity,offered_copper,requested_item_id,requested_quantity,requested_copper)values(sender_member.party_id,auth.uid(),target_sender_character_id,recipient_member.user_id,target_recipient_character_id,target_offered_item_id,coalesce(target_offered_quantity,0),coalesce(target_offered_copper,0),target_requested_item_id,coalesce(target_requested_quantity,0),coalesce(target_requested_copper,0))returning*into offer;return offer;
end;$$;

create or replace function public.respond_player_trade_offer(target_offer_id uuid,target_action text)returns public.player_trade_offers language plpgsql security definer set search_path=''as $$
declare offer public.player_trade_offers%rowtype;sender_wallet public.character_wallets%rowtype;recipient_wallet public.character_wallets%rowtype;source_stack public.character_item_stacks%rowtype;item public.content_items%rowtype;remaining integer;
begin
  if target_action not in('accept','reject','cancel')then raise exception'invalid trade action';end if;select*into offer from public.player_trade_offers where id=target_offer_id for update;if offer.id is null then raise exception'trade not found';end if;
  if offer.status<>'pending'then raise exception'trade resolved';end if;if offer.expires_at<=now()then update public.player_trade_offers set status='expired',resolved_at=now()where id=offer.id returning*into offer;return offer;end if;
  if target_action='cancel'then if offer.sender_user_id<>auth.uid()then raise exception'sender required';end if;update public.player_trade_offers set status='canceled',resolved_at=now()where id=offer.id returning*into offer;return offer;end if;
  if offer.recipient_user_id<>auth.uid()then raise exception'recipient required';end if;if target_action='reject'then update public.player_trade_offers set status='rejected',resolved_at=now()where id=offer.id returning*into offer;return offer;end if;
  if not exists(select 1 from public.persistent_party_members where party_id=offer.party_id and character_id=offer.sender_character_id)or not exists(select 1 from public.persistent_party_members where party_id=offer.party_id and character_id=offer.recipient_character_id)then raise exception'party changed';end if;
  if exists(select 1 from public.character_life_profiles where character_id in(offer.sender_character_id,offer.recipient_character_id)and status<>'alive')then raise exception'character unavailable';end if;
  select*into sender_wallet from public.character_wallets where character_id=offer.sender_character_id for update;select*into recipient_wallet from public.character_wallets where character_id=offer.recipient_character_id for update;if sender_wallet.balance_copper<offer.offered_copper or recipient_wallet.balance_copper<offer.requested_copper then raise exception'insufficient funds';end if;
  if offer.offered_quantity>0 then select*into item from public.content_items where id=offer.offered_item_id;if item.rarity='soulbound'or coalesce((item.properties->>'tradeable')::boolean,true)=false then raise exception'soulbound item';end if;select*into source_stack from public.character_item_stacks where character_id=offer.sender_character_id and content_item_id=offer.offered_item_id for update;if source_stack.id is null or source_stack.quantity<offer.offered_quantity then raise exception'insufficient items';end if;remaining:=source_stack.quantity-offer.offered_quantity;if remaining=0 then delete from public.character_item_stacks where id=source_stack.id;else update public.character_item_stacks set quantity=remaining,updated_at=now()where id=source_stack.id;end if;insert into public.character_item_stacks(character_id,user_id,content_item_id,quantity,acquired_unit_value)values(offer.recipient_character_id,offer.recipient_user_id,offer.offered_item_id,offer.offered_quantity,source_stack.acquired_unit_value)on conflict(character_id,content_item_id)do update set quantity=public.character_item_stacks.quantity+excluded.quantity,updated_at=now();end if;
  if offer.requested_quantity>0 then select*into item from public.content_items where id=offer.requested_item_id;if item.rarity='soulbound'or coalesce((item.properties->>'tradeable')::boolean,true)=false then raise exception'soulbound item';end if;select*into source_stack from public.character_item_stacks where character_id=offer.recipient_character_id and content_item_id=offer.requested_item_id for update;if source_stack.id is null or source_stack.quantity<offer.requested_quantity then raise exception'insufficient items';end if;remaining:=source_stack.quantity-offer.requested_quantity;if remaining=0 then delete from public.character_item_stacks where id=source_stack.id;else update public.character_item_stacks set quantity=remaining,updated_at=now()where id=source_stack.id;end if;insert into public.character_item_stacks(character_id,user_id,content_item_id,quantity,acquired_unit_value)values(offer.sender_character_id,offer.sender_user_id,offer.requested_item_id,offer.requested_quantity,source_stack.acquired_unit_value)on conflict(character_id,content_item_id)do update set quantity=public.character_item_stacks.quantity+excluded.quantity,updated_at=now();end if;
  if offer.offered_copper<>offer.requested_copper then update public.character_wallets set balance_copper=balance_copper-offer.offered_copper+offer.requested_copper,updated_at=now()where character_id=offer.sender_character_id returning*into sender_wallet;update public.character_wallets set balance_copper=balance_copper+offer.offered_copper-offer.requested_copper,updated_at=now()where character_id=offer.recipient_character_id returning*into recipient_wallet;insert into public.wallet_transactions(character_id,user_id,delta_copper,balance_after,reason)values(offer.sender_character_id,offer.sender_user_id,offer.requested_copper-offer.offered_copper,sender_wallet.balance_copper,'แลกเปลี่ยนกับสมาชิกปาร์ตี้'),(offer.recipient_character_id,offer.recipient_user_id,offer.offered_copper-offer.requested_copper,recipient_wallet.balance_copper,'แลกเปลี่ยนกับสมาชิกปาร์ตี้');end if;
  update public.player_trade_offers set status='accepted',resolved_at=now()where id=offer.id returning*into offer;return offer;
end;$$;
revoke all on function public.create_player_trade_offer(uuid,uuid,bigint,integer,integer,bigint,integer,integer)from public;revoke all on function public.respond_player_trade_offer(uuid,text)from public;grant execute on function public.create_player_trade_offer(uuid,uuid,bigint,integer,integer,bigint,integer,integer)to authenticated;grant execute on function public.respond_player_trade_offer(uuid,text)to authenticated;
alter publication supabase_realtime add table public.player_trade_offers;
