create table public.status_effect_templates(id bigint generated always as identity primary key,slug text not null unique,name_th text not null,effect_type text not null check(effect_type in('buff','debuff')),description_th text not null,default_duration smallint not null check(default_duration between 1 and 99),max_stacks smallint not null default 1 check(max_stacks between 1 and 10),modifiers jsonb not null default '{}',active boolean not null default true);
create table public.character_status_effects(id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,template_id bigint not null references public.status_effect_templates(id),name_th text not null,effect_type text not null check(effect_type in('buff','debuff')),description_th text not null,duration_remaining smallint not null check(duration_remaining between 1 and 99),stacks smallint not null default 1 check(stacks between 1 and 10),modifiers jsonb not null default '{}',source text not null default 'unknown',applied_at timestamptz not null default now(),unique(character_id,template_id));
alter table public.status_effect_templates enable row level security;alter table public.character_status_effects enable row level security;
create policy "Players can read status templates" on public.status_effect_templates for select to authenticated using(active);create policy "Players can read their effects" on public.character_status_effects for select to authenticated using(user_id=auth.uid());
insert into public.status_effect_templates(slug,name_th,effect_type,description_th,default_duration,max_stacks,modifiers)values
('blessed','พรแห่งแสง','buff','เพิ่มความแม่นยำและพลังใจ',3,1,'{"attack":1,"wisdom_save":1}'),('haste','เร่งความเร็ว','buff','เคลื่อนไหวไวและหลบหลีกดีขึ้น',2,1,'{"speed":10,"armor_class":1}'),('battle-focus','สมาธิรบ','buff','สะสมพลังโจมตีจากความต่อเนื่อง',3,3,'{"attack_per_stack":1}'),('regeneration','ฟื้นฟู','buff','ฟื้นพลังชีวิตเมื่อจบเทิร์น',4,1,'{"heal_per_turn":2}'),('fire-ward','เกราะเพลิง','buff','ลดความเสียหายจากไฟ',5,1,'{"fire_resistance":25}'),
('poisoned','ติดพิษ','debuff','เสียพลังชีวิตเมื่อจบเทิร์น',4,3,'{"damage_per_stack":1}'),('slowed','เชื่องช้า','debuff','ความเร็วและการหลบหลีกลดลง',2,1,'{"speed":-10,"armor_class":-1}'),('frightened','หวาดกลัว','debuff','เสียเปรียบเมื่อเผชิญต้นเหตุความกลัว',2,1,'{"attack":-1}'),('burning','ลุกไหม้','debuff','ได้รับความเสียหายไฟต่อเนื่อง',3,3,'{"fire_damage_per_stack":2}'),('silenced','ถูกผนึกเสียง','debuff','ไม่สามารถใช้เวทที่ต้องร่ายด้วยเสียง',2,1,'{"verbal_spells":false}');

create or replace function public.apply_character_status(target_character_id uuid,target_template_id bigint,target_source text)
returns public.character_status_effects language plpgsql security definer set search_path='' as $$declare character public.characters%rowtype;template public.status_effect_templates%rowtype;effect public.character_status_effects%rowtype;begin select * into character from public.characters where id=target_character_id and user_id=auth.uid();if character.id is null then raise exception 'character not found';end if;select * into template from public.status_effect_templates where id=target_template_id and active;if template.id is null then raise exception 'template not found';end if;insert into public.character_status_effects(character_id,user_id,template_id,name_th,effect_type,description_th,duration_remaining,stacks,modifiers,source)values(target_character_id,auth.uid(),template.id,template.name_th,template.effect_type,template.description_th,template.default_duration,1,template.modifiers,left(coalesce(nullif(trim(target_source),''),'unknown'),60))on conflict on constraint character_status_effects_character_id_template_id_key do update set stacks=least(public.character_status_effects.stacks+1,template.max_stacks),duration_remaining=greatest(public.character_status_effects.duration_remaining,template.default_duration),source=excluded.source returning * into effect;return effect;end;$$;
create or replace function public.tick_character_statuses(target_character_id uuid)
returns setof public.character_status_effects language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.characters where id=target_character_id and user_id=auth.uid())then raise exception 'character not found';end if;delete from public.character_status_effects where character_id=target_character_id and duration_remaining<=1;return query update public.character_status_effects set duration_remaining=duration_remaining-1 where character_id=target_character_id returning *;end;$$;
create or replace function public.remove_character_status(target_effect_id uuid)
returns void language plpgsql security definer set search_path='' as $$begin delete from public.character_status_effects where id=target_effect_id and user_id=auth.uid();if not found then raise exception 'effect not found';end if;end;$$;
revoke all on function public.apply_character_status(uuid,bigint,text) from public;revoke all on function public.tick_character_statuses(uuid) from public;revoke all on function public.remove_character_status(uuid) from public;grant execute on function public.apply_character_status(uuid,bigint,text) to authenticated;grant execute on function public.tick_character_statuses(uuid) to authenticated;grant execute on function public.remove_character_status(uuid) to authenticated;
